### ISSUE TITLE
Unfollow seems doesn't work

### ISSUE THREAD

**Issue by rumahbudi** [LevPasha/instabot.py#100]
Helo, 

unfollow does not work ?

This is my settings

` like_per_day=1000,
               comments_per_day=50,
               tag_list=['tag1', 'tag2', 'tag3',],
               max_like_for_one_tag=50,
               follow_per_day=150,
               follow_time=5*60*60,
               unfollow_per_day=150,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0) `

Console Log :
Unfollow seems doesn't work

Get media id by tag: tag1
Trying to like media: 1271586614493640682
Liked: 1271586614493640682. Like 1.
Trying to follow: 3318105574
Followed: 3318105574 1.
Trying to like media: 1271584453856657042
Liked: 1271584453856657042. Like 2.
Trying to like media: 1271580154963068402
Liked: 1271580154963068402. Like 3.
Trying to like media: 1271578838665382348
Liked: 1271578838665382348. Like 4.
Trying to like media: 1271578244829546065
Liked: 1271578244829546065. Like 5.
Trying to like media: 1271559076440504094
Liked: 1271559076440504094. Like 6.
Trying to like media: 1271557475677483629
Liked: 1271557475677483629. Like 7.
Trying to like media: 1271546327944355105
Liked: 1271546327944355105. Like 8.
Trying to like media: 1271545618141763914
Liked: 1271545618141763914. Like 9.
Trying to follow: 3243901238
Followed: 3243901238 2.
Trying to like media: 1271544837120941308
Liked: 1271544837120941308. Like 10.
Trying to like media: 1271538489150113357
Liked: 1271538489150113357. Like 11.
Trying to like media: 1271536442702540979
Liked: 1271536442702540979. Like 12.
Trying to like media: 1271535312596204660
Liked: 1271535312596204660. Like 13.
Trying to like media: 1271533288753705074
Liked: 1271533288753705074. Like 14.
Trying to like media: 1271521035627772277
Liked: 1271521035627772277. Like 15.
Get media id by tag: tag2
Trying to like media: 1271607165576607133
Liked: 1271607165576607133. Like 16.
Trying to like media: 1271605295734585111
Liked: 1271605295734585111. Like 17.
Trying to like media: 1271594099785730478
Liked: 1271594099785730478. Like 18.

**Comment by skynyd** [comment]
it just starts after 5 hours due to "follow_time=5*60*60"
btw: you should edit the tags to real ones

**Comment by rumahbudi** [comment]
Solved
