### ISSUE TITLE
Login Error, too many attempts with incorrect password.

### ISSUE THREAD

**Issue by sephco** [LevPasha/instabot.py#104]
So after logging in with the incorrect login password, IG sent a security code to login. Now, every time I try to login in on different browsers manually sends a new text with a new security code. ( I thought logging into all my browsers and confirming my identity would fix the issue)

Right now I can't seem to login through instabot - I keep getting "Login error! Connection error!'. Which is probably because Apache is getting the same error and being requested to input a security code sent via text. 

Anyone know how I could fix this? Maybe by placing something in the code to deal with it when it gets that URL?

Side note: I've altered a lot of the code but the login methods and arguments have remained pretty much unaltered. 

**UPDATE:** It was do to account having two-factor authentication turned on. Turned it of and problem solved!

**Comment by ByBilal** [comment]
thanks so much for the update, that tid bit helped
