### ISSUE TITLE
SSH or Graphical Interface

### ISSUE THREAD

**Issue by alexlaza10** [LevPasha/instabot.py#109]
Hey Guys, 

my bot works fine and i want to thank every contributor especially Levpaha. 
Iam in use of a raspberry pi 2 with a graphical interface where i open serval Terminals to use multipe Bots.

My qustion is. Is there an easier way to start the bot ? with SSH ? Can i start serval instabot.py files in realtime in SSH? Because at the gui i require one Terminal for each bot.

Example: `python instbot1.py & python instabot2.py & python instabot3.py`

is there any way to controle them , if there working fine?

**Comment by LevPasha** [comment]
@alexlaza10 hi, i think you can create bash file, that run all of your script. Use google.

**Comment by LevPasha** [comment]
@alexlaza10 hi! I think this is question not about bot. I run it from ssh to, one process for one account. I think you can write one file with bash command (google it), and run this file.

**Comment by FluffyPancakes** [comment]
You can use screen to open multiple terminals that would run the code each. :)
