### ISSUE TITLE
bot.like_all_exist_media() not working

### ISSUE THREAD

**Issue by ThomasMW** [LevPasha/instabot.py#11]
This example does not seem to work:

```
    bot = InstaBot('username', 'password')
    bot.get_media_id_by_tag('lik4like')
    bot.like_all_exist_media(1)
```
Login succeeds, then getting the media also works, but liking fails for some reason. I get no console output.

Using the bot.auto_mod() method works fine though, but I would like to use the first method so I always like the first picture that comes up in the search.

**Comment by ThomasMW** [comment]
I found the problem.

Whenever the picture is already liked it doesn't return any output. However, I want to like the first picture everytime I search for a tag. How do I clear the list after I've liked the first picture in the list?

**Comment by LevPasha** [comment]
Hi! Maybe you need to change `more_than_likes=10`. When you load some media by tag ` get_media_id_by_tag` you load 20 media (look at picture). 1 block - is popular of this tag, 2 block - newest.  
If you want to like photo #0 - you write `bot.like_all_exist_media(1)` (yes you right), buy defoult value of `more_than_likes=10` - don't give you like media with like count > 10. In next commit i make 0 = infifnty likes, but now you should write like this `bot = InstaBot('username', 'password', more_than_likes=9999999)`
![1](https://cloud.githubusercontent.com/assets/9821835/12990466/946eee30-d11b-11e5-8ea6-f7633b167a39.png)

**Comment by LevPasha** [comment]
Add new commit eea1439b8463d01da8327f14b509cd2fec8bf1f2 `more_than_likes` change to `media_max_like`. Set it to 0, for like media with infinity likes.

**Comment by ThomasMW** [comment]
I fixed it using 
````
bot.like(bot.media_by_tag[0]['id'])
````
and putting it into a loop.
