### ISSUE TITLE
Liking seems to not be working anymore?

### ISSUE THREAD

**Issue by ThomasMW** [LevPasha/instabot.py#110]
Since two days it seems that liking a post doesn't work anymore using the bot.

Tried on multiple accounts, no bans. Anyone else having this?

**Comment by umbrellr** [comment]
Glad it's not just me, thought I had been banned... 
My console just repeats "Get media id by tag: etc"

**Comment by velvetflower** [comment]
Hmm... Everything works for me.

**Comment by ThomasMW** [comment]
@umbrellr Same for me.

**Comment by orchestor** [comment]
Just wondering what's the use case for the Instagram bot.

**Comment by ThomasMW** [comment]
@orchestor what?

**Comment by orchestor** [comment]
@ThomasMW

I mean how powerful it can be in the instagram platform.

**Comment by LevPasha** [comment]
I have no any problem. What hastag do you use?

**Comment by LevPasha** [comment]
Hmmm... Look like instagram change something https://www.instagram.com/explore/tags/cat/ try to increase: `media_max_like and media_min_like`

**Comment by ThomasMW** [comment]
I found the problem. I was using the hashtag #like4like, but Instagram has currently hidden recent posts because some were violating community guidelines. So the bot couldn't retrieve the photo.

Other hashtags work fine though.
