### ISSUE TITLE
Not Finding Media

### ISSUE THREAD

**Issue by 2kew** [LevPasha/instabot.py#111]
I have been using this and it works great. One day I try and use it and all I see is

"Get media id by tag: instagood
Get media id by tag: instagood
Get media id by tag: instagood
Get media id by tag: instagood
Get media id by tag: instagood"

It repeats this with all different hashtags and such. Not sure what the issue is. Seems like it can't find media id to like. I am using this only to like posts. I do not use for comments or follows.

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/issues/110
