### ISSUE TITLE
Get Media information

### ISSUE THREAD

**Issue by alexlaza10** [LevPasha/instabot.py#112]
Hello guys, 

i got one question. The bot starts normaly, but at some point he skips media tags. 

`Get media it by tag: books
Get media id by tag: books
Get media id by tag: rio 
Try to like media: 164646514857631
Get media id by tag: finally
Get media id by tag: wild`

Is this some Issue in the skript ? the hastags are very common. 

Thanks

**Comment by LevPasha** [comment]
Hmmm... Look like instagram change something (video now have view count) https://www.instagram.com/explore/tags/cat/ try to increase: media_max_like

**Comment by alexlaza10** [comment]
Yeah,  but media doesnt mean automaticallly video or picture ?

**Comment by LevPasha** [comment]
increase: media_max_like

**Comment by alexlaza10** [comment]
ok, thanks in advance , i will report you :)
