### ISSUE TITLE
Bot doens't work

### ISSUE THREAD

**Issue by Invochu** [LevPasha/instabot.py#113]
It keeps saying "Get media id by tag:"Tag" over and over again. I've tried changing ` media_max_like=` and other settings. But it still is not working. Help?

![helo](https://cloud.githubusercontent.com/assets/20051987/16207726/fdace798-372e-11e6-8e23-bcc4ce30de4e.png)

**Comment by psam25** [comment]
#110

**Comment by Invochu** [comment]
It randomly started working now! yes!
