### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by Maxie01** [LevPasha/instabot.py#116]
I keep getting this

http://i.imgur.com/1Owotkj.png

help?

**Comment by LevPasha** [comment]
@Maxie01 what python version do you use?

**Comment by Maxie01** [comment]
3.5

**Comment by Maxie01** [comment]
Also sorry for the late reply, forgot I started this issue

**Comment by LevPasha** [comment]
You have same problem now?

**Comment by polaroi8d** [comment]
@Maxie01 do you still have these problems? If not we are close this issue.
