### ISSUE TITLE
Some code style

### ISSUE THREAD

**Issue by sikrinick** [LevPasha/instabot.py#117]
You have this code in `def get_media_id_by_tag()`
```
                    finder_text_start = ('<script type="text/javascript">'
                                         'window._sharedData = ')
                    finder_text_start_len = len(finder_text_start)-1
                    finder_text_end = ';</script>'

                    all_data_start = text.find(finder_text_start)
                    all_data_end = text.find(finder_text_end, all_data_start + 1)
                    json_str = text[(all_data_start + finder_text_start_len + 1) \
                                   : all_data_end]
                    all_data = json.loads(json_str)
```
`len(finder_text_start)` shouldn't be decremented by 1 as it incremented by 1 in the `json_str`

Also, in `def like()` there is a useless row `last_liked_media_id = media_id`

**Comment by LevPasha** [comment]
@sikrinick hi!
Do you have some error with my code? I don't remeber why i make `finder_text_start_len = len(finder_text_start)-1` - if you think it is useless - make pull request, and i test your code. THX!
