### ISSUE TITLE
Question about "nodes"

### ISSUE THREAD

**Issue by sikrinick** [LevPasha/instabot.py#118]
I am using your bot code source rewriting it to Java (Android). Currently, I have a problem with getting photos by tag. I rewrote your `def get_media_id_by_tag()` in Java, but `https://www.instagram.com/explore/tags/%s` doesn't return more than 18 nodes, as it is showing in web version. Once, your version returned 19 nodes.
Can I somehow get more then 18 nodes? Or go to next page?

**Comment by LevPasha** [comment]
@sikrinick hi, i have no time to do it. If you have time you can try to read your `browser => instagram` (when you press next page) requests and capture pagination.
