### ISSUE TITLE
Comment & Follow

### ISSUE THREAD

**Issue by jtclark84** [LevPasha/instabot.py#12]
How do you comment and follow without knowing the user_id or media_id? I understand you can get.media.id.by.tag, but how about user_id? In your example you just have it entered already.

**Comment by LevPasha** [comment]
Hi i answer you in #8 

FInd 192 str in last version of InstaBot https://github.com/LevPasha/instabot.py/blob/master/instabot.py#L192
`like = self.like(self.media_by_tag[i]['id'])`
and add after it 
`comment = self.comment(self.media_by_tag[i]['id'], 'Your comment')`
The var `self.media_by_tag[i]['id']` - have media_id, you liked. You can comment it.

About user_id - now it is no opportunity to follow, except user_id. Change it in future.

**Comment by nivong** [comment]
and how would that look inside the py ?
```
bot = InstaBot('login', 'password',
               like_in_day=100000,
               more_than_likes=5,
               tag_list = ['like', 'follow', 'girls'],
               max_like_for_one_tag=50,
               log_mod = 1)
bot.comment('media_id', 'Insert awesome shit here')
bot.auto_mod()
```

Like that?

**Comment by LevPasha** [comment]
@nivong `'media_id'` must have some value. When you run `bot.get_media_id_by_tag("cat")` - it create var `self.media_by_tag`. In this var on `self.media_by_tag[i]['id']` - locate value of `'media_id'`

Best way to commet all, that you like is:

If you use `bot.auto_mod()` fInd str in last version of InstaBot:
`like = self.like(self.media_by_tag[i]['id'])`
and add after it 
`comment = self.comment(self.media_by_tag[i]['id'], 'Your comment')`

or like your example:
```python
bot = InstaBot('login', 'password')
bot.get_media_id_by_tag("cat")
# there we have bot.media_by_tag[0] to bot.media_by_tag[20]
bot.comment(bot.media_by_tag[5]['id'], 'Insert awesome shit here')
# we comment 6 media_id
```

**Comment by LevPasha** [comment]
@jtclark84 @nivong look new commit for you eea1439b8463d01da8327f14b509cd2fec8bf1f2 str 202-203.

**Comment by nivong** [comment]
It worked thanks :) @LevPasha i am currently overhauling the readme with better english and better examples with explanations :)

**Comment by LevPasha** [comment]
@nivong Thank you, that mock on my English ))

**Comment by i-diot** [comment]
При указании id пользователя,  
bot.follow('id1', 'id2', 'id3',)
Ошибку выдает 
```
Traceback (most recent call last):
  File "example.py", line 37, in <module>
    bot.follow('1784434763', '419284352', '227747340',)
TypeError: follow() takes exactly 2 arguments (4 given)
Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:08.799784
Logout success!
Exception KeyError: KeyError(140380015231872,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

Правильно указываю ?
