### ISSUE TITLE
no module named instabot

### ISSUE THREAD

**Issue by AndyB1928** [LevPasha/instabot.py#120]
Hey,

i can't figure out why i'm getting this error..

user@user ~/Documents $ python Complete.py
Traceback (most recent call last):
  File "Complete.py", line 642, in <module>
    from instabot import InstaBot
ImportError: No module named instabot

any help? i'm sure there is a simple fix that i'm missing

**Comment by LevPasha** [comment]
@AndyB1928 this issue not about instabot.

**Comment by AndyB1928** [comment]
Maybe I need to clarify. Complete.py is the instabot, I've added the login too, it's just a different name.

**Comment by LevPasha** [comment]
Maybe I need to clarify too. All code that I present - is work code. If you change it, or have some error not with my code - find answer in google. If you need a personal consultation - you can hire me.

**Comment by tbudd23** [comment]
Hey I have this same issue and I kept all settings default.  

C:\>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
ImportError: No module named 'instabot'

**Comment by tbudd23** [comment]
please help!! :)

**Comment by shahsarick** [comment]
@tbudd23 just move example.py into src folder ;)

**Comment by kamimarthyn** [comment]
i have the same problem please help me 
it says module not found error: no module name requests

**Comment by yeye412** [comment]
Same issue :\
