### ISSUE TITLE
Suddenly keep getting 400 error 

### ISSUE THREAD

**Issue by farhang87** [LevPasha/instabot.py#123]
Have been using it for 2 weeks, not being blocked in the last 7 days. 

With my main account I keep getting 400 error messages whenever it tries to like a picture. This doesn't happen when running with my other account. Tried with different hashtags, but still same problem. I am not blocked or anything, I can still like via my the mobile app.

I haven't changed the original script or anything, and just started happening overnight after having worked properly for a week.

You think Instagram tracked it down somehow and actively blocks with my account and specific connection?

**Comment by LevPasha** [comment]
@farhang87 hi! I think you have "Like ban". Wait about day and try again. I think you can't like in mobile app (refresh after like and check - i think like disappear).

How many `like per day` do you use?

**Comment by farhang87** [comment]
I think it indeed was a Like Ban. But something has changed within Instagram on this part. Because I was definitely able to continue liking on 2 different mobile apps and another bot (instagress). Couple days later same thing happened, I was blocked on 1 mobile app but could continue liking on another mobile. 

What kind of product does Instagram think the bot is on, web?

**Comment by LevPasha** [comment]
@farhang87 https://github.com/LevPasha/instabot.py/blob/master/instabot.py#L45

**Comment by kaxil** [comment]
@LevPasha Is the bot not working now ? The api seems to fail when fetching user_followers

**Comment by LevPasha** [comment]
@kaxil api?

**Comment by kaxil** [comment]
@LevPasha Yes, the process of fetching followers is not returning anything

**Comment by LevPasha** [comment]
You talk about this? https://github.com/LevPasha/instabot.py/issues/91
