### ISSUE TITLE
Follow user followers

### ISSUE THREAD

**Issue by coma123** [LevPasha/instabot.py#125]
hello. thank you for this awesome bot.
I want one thing and can it be done? for example:
First day: I am giving to bot username and it follows his followers with limit (100 in hour).
Second day: bot gets list of people which I am following and unfollows them from bottom of list. with limit (100 in hour).
can bot do this thing?
P.S. sorry for my poor english

**Comment by LevPasha** [comment]
@coma123 you can't do it "from box", you should write your code for this.
