### ISSUE TITLE
Nr. of unfollow seems to be dependent on nr. of follows

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [LevPasha/instabot.py#126]
I have configured my bot to unfollow twice the amount of follows per day. But nonetheless, it does only approximately unfollow the same amount of follows. Any idea why this happens?

**Comment by alfazick** [comment]
@Karlheinzniebuhr Hello can you told me where you set number of unfollows.
My version doesn't do unfollows at all. I can figure out why

**Comment by Karlheinzniebuhr** [comment]
![image](https://cloud.githubusercontent.com/assets/5278928/16732573/2924ba54-477e-11e6-9c47-b2b144961ac5.png)

**Comment by alfazick** [comment]
`From instabot import InstaBot

bot = InstaBot(login="login", password="password",
               like_per_day=1000,
               comments_per_day=0,
               tag_list=['follow4follow', 'f4f', 'cute'],
               max_like_for_one_tag=50,
               follow_per_day=150,
               follow_time=5*60*60,
               unfollow_per_day=1500,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0)

bot.new_auto_mod()`

this example.py file And it doesn't do unfollowing as far as i see

**Comment by Karlheinzniebuhr** [comment]
As of right now, it unfollows only the ones, the script previously followed. It should be changed to unfollow arbitrary profiles

**Comment by alfazick** [comment]
ok thank you  I understand so in what file I need to change to do it?

**Comment by Karlheinzniebuhr** [comment]
In the instabot.py file, if you manage to get a list of all followers from instagram and put that in the bot_follow_list, then it would have the mentioned behaviour. 
But even better would be to modify the api of instabot and instead use an aditional parameter like "absolute_unfollow_per_day", to differentiate it from the "unfollow_per_day" parameter. 
![image](https://cloud.githubusercontent.com/assets/5278928/16734507/16361f66-4786-11e6-8931-c0d2d3ba28e8.png)

**Comment by alfazick** [comment]
ok thank you

**Comment by LevPasha** [comment]
@Karlheinzniebuhr @alfazick bot in auto mod can unfollow only user that BOT follow.

**Comment by alfazick** [comment]
@LevPasha so what is a logic behind unfollows for example if I choose follow to 1000 and unfollow to 1000, why after 5*60*60 started to unfollow with same distribution. Today I noticed it unfollows properly but, I leave script unfinished.

**Comment by Karlheinzniebuhr** [comment]
so In what mode does it have to run in order to unfollow any user?  @LevPasha

**Comment by LevPasha** [comment]
@alfazick if you follow user and unfollow him from second - this give you nothig. If you unfollow him from few hours - hi can follow back.
@Karlheinzniebuhr there is now mode like you want.

**Comment by Karlheinzniebuhr** [comment]
wow great @LevPasha thanks a lot
