### ISSUE TITLE
follow again some one already unfollowed

### ISSUE THREAD

**Issue by amgworkshop** [LevPasha/instabot.py#128]
Hi, thank you for this script i really appreciate that you take time to make it and share it with us.
i just wanna know if the bot follow again those that has been unfollowed?
Thanks!

**Comment by LevPasha** [comment]
Bot get media id by tag, and follow owner of this media. Yes hi can follow one user 1000 times.

**Comment by amgworkshop** [comment]
Could a user unfollow and block me if it keep follow and unfollow him? is there a way to make a list of all the users i follow and never follow them again after unfollowing them?

**Comment by LevPasha** [comment]
Instagram make nothing if you try to follow user, that you follow before. You can code this and share with us.
