### ISSUE TITLE
Only Like _if_more_than.

### ISSUE THREAD

**Issue by Tonners15** [LevPasha/instabot.py#129]
How can you like only photos if they are more then 100 likes for example? 

media_max_like=10,
media_min_like=0,

But I feel like it still likes all the tags and sometimes it likes weird stuff hah and it likes it right when they post it. 

And is there an option to following only people who are over lets say 10k?

**Comment by LevPasha** [comment]
media_max_like=10 and media_min_like=0 work like they must work. No there is no option follow people buy some settings.
