### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by umuthan** [LevPasha/instabot.py#135]
Hi!

How can i add emoji in comment text?

Bytes or unicode in this page http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by TTAAEELL** [comment]
Any progress?

**Comment by polaroi8d** [comment]
No @TTAAEELL

**Comment by ivancalax** [comment]
Someone has tested https://pypi.python.org/pypi/emoji/ ?

**Comment by drewhga** [comment]
Emoji support?
I'm able to comment with emojis fine

**Comment by virginsince1997** [comment]
Can you please give your modified instabot.py (comment)

**Comment by ivancalax** [comment]
@drewhga please, can you share how to comment with emojis?

**Comment by TTAAEELL** [comment]
@drewhga Sharing is caring.

**Comment by kantona80** [comment]
copy the emoticons that you want from a comment in instagram web site and
paste in the source code, in comment section.

2016-10-26 0:23 GMT+02:00 TAEL <notifications@github.com>:

**Comment by drewhga** [comment]
I used Android marshmallow with qpython.
So something like this worked for me...

bot.comment(12347894, Nice! ✌✌)

So it should also work with the itertools..

With a PC you should look up the supported Unicode emoji or just copy and paste from sites like 

http://www.copyandpasteemoji.com/

**Comment by umuthan** [comment]
thanks!
