### ISSUE TITLE
slow likes

### ISSUE THREAD

**Issue by v78007800** [LevPasha/instabot.py#138]
Could anybody help me, please??
Likes are coming very slowly (1 per hour or so).

_bot = InstaBot('XX', 'XXX',
               like_per_day=1000,
               media_max_like=80,
               media_min_like=2,
               tag_list = ['art', 'sketch'],
               max_like_for_one_tag=500,
               log_mod = 0)
bot.auto_mod()_

I get only a long list:
Get media id by tag: sketch
Get media id by tag: sketch
Get media id by tag: sketch
Get media id by tag: sketch
Get media id by tag: sketch
Get media id by tag: art
Get media id by tag: sketch
Get media id by tag: art
Get media id by tag: art
Get media id by tag: sketch
Get media id by tag: sketch

**Comment by polaroi8d** [comment]
You are using very rare hashtag, if you want to your bot like more photos, use familiar hashtags, like #party #friends #awesome or you can google it for the top 100 hashtags in instagram.

**Comment by LevPasha** [comment]
@polaroi8d yes!
