### ISSUE TITLE
Phone number code

### ISSUE THREAD

**Issue by mmeftah** [LevPasha/instabot.py#139]
Hello and thank you for the great work!

I have noticed that after a period of great working, the bot is stop (like banned) and they ask for verify code by phone number.
I am forced to do it manually for the bot to start again.
Have you ever faced that?

A solution may be to use online sms number and make it automatically gets the code ?

Thank you

**Comment by polaroi8d** [comment]
Limited the like per day, if you are like too much photos, instagram will bann you.

**Comment by LevPasha** [comment]
@mmeftah how many likes, follow and etc you make per day?

**Comment by polaroi8d** [comment]
Inactive issue. Closed
