### ISSUE TITLE
Need help running this in qpython

### ISSUE THREAD

**Issue by dakraziest** [LevPasha/instabot.py#14]
I have been trying to run this code on qpython android but it keeps throwing error 
I m new to this programming language so I might be doing everything wrong but would appreciate if someone can help me run this on a mobile device

**Comment by nivong** [comment]
You can't run it on a mobile and you should learn basic programming skills if you want to use it.

**Comment by dakraziest** [comment]
Okay,thanks

**Comment by LevPasha** [comment]
@dakraziest @nivong hi! I think instabot can work on `qpython`. I don't have android to test, but i don't see any reason why it can't work (if you can install `request` lib to `qpython`).

@dakraziest  if you want some help - show your error (first google it).

**Comment by dakraziest** [comment]
Thanks dear. It works flawlessly on qpython not sure why wasn't working on qpython3.
Thumbs up for the awesome code
