### ISSUE TITLE
Comments code

### ISSUE THREAD

**Issue by v78007800** [LevPasha/instabot.py#142]
Hi! Could you help please with coding for comments by tag? 
I want to comment tab 'black'.  Is this code true? How could I set my own list of comments?

bot = InstaBot('log', 'pass',
                comments_per_day=50,
                tag_list=['black'],
                log_mod = 0)

Thanks!

**Comment by LevPasha** [comment]
Comment string have random generation from key words arrays: https://github.com/LevPasha/instabot.py/blob/master/instabot.py#L502 Change it like you need.
