### ISSUE TITLE
Instabot wont start

### ISSUE THREAD

**Issue by wbx32** [LevPasha/instabot.py#144]
Hello could you please tell me why the bot not start?
The example is working but the instabot not? 

>>> 
 **RESTART: C:\Users\XXX\Desktop\instabot.py-master\instabot.py-master\instabot.py** 
>>> 

Edit
Now I get an error in Example to:

Traceback (most recent call last):
  **File "C:\Users\XXX\Desktop\instabot.py-master\instabot.py-master\example.py", line 16, in <module>
    log_mod=0)
TypeError: __init__() got multiple values for argument 'login'**

**Comment by juliandortmund** [comment]
did you put your credentials in quotes?

**Comment by wbx32** [comment]
self, login, password
so i deleted self 
login "xx", Password "XX"
with that?

**Comment by LevPasha** [comment]
@wbx32 see example, you have some sintaxis error.

**Comment by wbx32** [comment]
@LevPasha 
So when i run example.py it´s working, but when I run only instabot.py its not working?
Or do I need only example.py and instabot.py is only the settings ?

**Comment by LevPasha** [comment]
@wbx32 Instabot.py is a class. Expample execute program...

**Comment by MattHering** [comment]
It won't work for me. I just get a "Traceback (most recent call last):" and than a bunch of files and their line numbers, Anyone know what to do?
