### ISSUE TITLE
"InstaBot" is not defined??

### ISSUE THREAD

**Issue by jedougard** [LevPasha/instabot.py#147]
Why does python launcher say that??

**Comment by ierogliph** [comment]
Hi. How u start script?

**Comment by jedougard** [comment]
this is what I wrote: 
bot= InstaBot ('USER NAME', ' PASSWORD',    --> (NOT WRITTEN HERE OF COURSE)
               like_per_day=900,
               media_max_like=0,
               media_min_like=0,
               follow_per_day=150,
               follow_time=24*60*60,
               unfollow_per_day=145,
               comments_per_day=0,
               tag_list=['bnw', 'landscape', 'clouds', 'simplicity', 'menfashion', ],
               max_like_for_one_tag=5,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod = 0)
bot.auto_mod()

I opened the file with python launcher but it says:  NameError: name 'InstaBot' is not defined

I don't understand why

**Comment by ierogliph** [comment]
Open Windows PowerShell. Write command:
cd cd C:\...\instabot.py-master
python example.py

**Comment by nvprophecy** [comment]
I am getting the same error.

![image](https://user-images.githubusercontent.com/32855258/39141124-c8ccd254-46f4-11e8-896d-f53be7c19c6b.png)

![image](https://user-images.githubusercontent.com/32855258/39141184-0034c60c-46f5-11e8-80c5-c19745b2b624.png)
