### ISSUE TITLE
Comment list

### ISSUE THREAD

**Issue by shaharbukra** [LevPasha/instabot.py#15]
hey,
is it possible to create comment list and then randomly chose between them? 
instead of sending the same comment...

and thanks for the bot 
work well!!
Shahar.

**Comment by LevPasha** [comment]
@shaharbukra hi! You can do it youself, like:
```python
c_list= ['a', 'b', 'c', 'd', 'e']
comment = bot.comment(media_by_tag, random.choice(c_list))
```
