### ISSUE TITLE
Login error! Connection error!

### ISSUE THREAD

**Issue by cokete** [LevPasha/instabot.py#150]
I am getting this error.

"Login error! Connection error!"

Trying on my MacOS with Python3 and in PythonAnywhere.

**Comment by polaroi8d** [comment]
@cokete do you have internet? Maybe you add the wrong password?

**Comment by cokete** [comment]
Yes, @polaroi8d of course that I have internet. The firewall is disabled now, but still not working.

**Comment by polaroi8d** [comment]
Check out the #122 issue.

**Comment by cokete** [comment]
I don't have "Two-factor authentication" enabled @polaroi8d

**Comment by cokete** [comment]
Solved! I entered the instagram app and had a message. I have accepted the confirmation message and started to run.

**Comment by polaroi8d** [comment]
So you have an authentication.

**Comment by heartofdev** [comment]
Hi, I have the same problem since yesterday 
when i launch python example.py i have a message 
"Login error! Connection error!"

Trying on my MacOS with Python Version 2.7.14
