### ISSUE TITLE
Ignoring young accounts to avoid spam

### ISSUE THREAD

**Issue by sephco** [LevPasha/instabot.py#151]
As you know you end up liking/following etc on spam/porn accounts. Since most accounts like that get removed within about 30 days, is there a way to prevent liking/following/commenting on accounts that aren't at least, say, 90 days old?

I think that feature would GREATLY reduce spam!

**Comment by polaroi8d** [comment]
Good idea, but you can prevent it with a good hashtag usage, i think.

**Comment by LevPasha** [comment]
@sephco @polaroi8d there is no way to get account age by http.
