### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by littying** [LevPasha/instabot.py#154]
Follow rate seems to be quite slow and not all of them go through when the script claims they do, i'm now only getting a follow every 2-5 minutes now, says it's followed 265 but probably only has already done 40% of those, account isn't limited yet either, running on python 2.7.9 linux, no errors pop up.

**Comment by littying** [comment]
No longer work, i get 1 follow then no more will register, but in the console it'll say it's still following loads

**Comment by beben06** [comment]
Same issue here. I need to check if i have change something but it seems login/like still working but follow/unfollow is not working anymore

**Comment by LevPasha** [comment]
@littying check your settings, check for ban.
