### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Vianeysi** [LevPasha/instabot.py#157]
Why does python launcher say:
ImportError: No module named request

**Comment by msansoni** [comment]
You have not got 'requests' installed.

Depending on your python distribution you have installed you might be able to use PIP.
In your terminal/command prompt write:
"pip install requests"

Then try re-running.

**Comment by LevPasha** [comment]
@msansoni thx!

**Comment by gersanchez** [comment]
I have the error " importError: cannot import name InstaBot " any solutions? thanks!
