### ISSUE TITLE
Can't get it running

### ISSUE THREAD

**Issue by mateuswtg** [LevPasha/instabot.py#16]
Hey, I never tried to use python, it took me 30 minutes to figure out how to run the script, but I can't quite make it do anything
Where should I add the 'bot = InstaBot(...)'?
In the end of the instabot.py file?
I tried it several times and nothing happened, it didn't even get me an error
I really wanna use your bot, hope you see this post! 

Thanks

**Comment by mateuswtg** [comment]
I figured out where to put it, but now I'm getting the error:
"Insta Bot v0.05 start at 03.03.2016 05:34:
Try to login by outonismo...
Login error! Check your login data!
MacDoJappa:bot mateuswtg$ 
"
And I reseted my password several times and updated on the file and it still isn't working ):

**Comment by mateuswtg** [comment]
Made it work for now! 
It took me some hours to learn a bit of python, but I got it working <3

**Comment by LevPasha** [comment]
@mateuswtg glad for you!
