### ISSUE TITLE
Guide on unfollowpub.py

### ISSUE THREAD

**Issue by nivong** [LevPasha/instabot.py#161]
There is a `unfollowpub.py` (I have never used it) but from what I can understand it gets the followers, checks if the user follows if they don't then the bot will unfollow them (and won't like or comment or do anything else)
But how does it work? I need to input something here:
```
#some lists
newlist = []
endlist = []
followerslist = []
```
But what do I fill in here? What is a "list" ? someone cares to explain? @velvetflower

**Comment by nekfeu** [comment]
as you can read first it takes your followers, who you are following and make the difference in order to know who aren't following you anymore. But i admit i don't know where is the function set.difference...

**Comment by nivong** [comment]
You need to fill in the list things otherwise it will not work.

**Comment by nekfeu** [comment]
okay so set.difference is a system function working with list ! thanks

**Comment by PabloStrange** [comment]
hmm, i also want to know how to use it ...

**Comment by nekfeu** [comment]
ahahah

**Comment by davisonio** [comment]
@LevPasha

**Comment by manguszta** [comment]
Same issue.

('Number of unnecessary subscriptions:', 0, '\n')
All done.
Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:04.916000
Logout success!

**Comment by LevPasha** [comment]
@nivong @nekfeu @manguszta @davisonio 
Problem is that UserInfo not work now...

This list create from UserInfo (that not work now). Get all you following:
```python
newlist = []
```

This list create from UserInfo (that not work now). Get all of your followers:
```python
followerslist = []
```

This list must save favorites followers (list of id):
```python
favorites = ['111','222','333']
```

Then - find difference and unfollow:
```pyhon
endlist = set.difference(set(newlist), set(favorites), set(followerslist))
```
