### ISSUE TITLE
My bot can't give comment :(

### ISSUE THREAD

**Issue by howardlie** [LevPasha/instabot.py#163]
hello, I set up everything and run but bot keep showing "Except on comment!" problem. But I can still manually add comment from instagram.com directly. Please help me :smile:  
It can't give comment even with the default settings, I think there are nothing wrong with the code. Thank you.

**Comment by howardlie** [comment]
looks like I got banned... any setting recommendation to not get banned? I only want to comment on people's post. Thank you

**Comment by LevPasha** [comment]
@howardlie sorry, try to find rate in google. I think 100-200 in day - is no problem. Maybe some user mark you as spam.
