### ISSUE TITLE
ink361 working?

### ISSUE THREAD

**Issue by dsshap** [LevPasha/instabot.py#164]
Looks like the (followers, following) endpoints in userinfo.py return 404... is anyone else seeing this?

If not, what am I missing with respect to getting those api's working?

**Comment by gonzalon** [comment]
@dsshap The API from Instagram changed, so all the services like ink361, stoped working =(

**Comment by LevPasha** [comment]
@dsshap @gonzalon but my bot work) 
@dsshap try this https://github.com/LevPasha/Instagram-bot-cs or this https://github.com/LevPasha/Instagram-API-python
