### ISSUE TITLE
Bot didnot work since today

### ISSUE THREAD

**Issue by MrJur1** [LevPasha/instabot.py#169]
Dear all,
the bot worked fine for about 1 week, and since today:
pls help

Instabot v1.0.1 started at 25.08.2016 11:12:

Trying to login as ****...

C:\Python27\lib\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Python27\lib\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
**** login success!
Get media id by tag: cute
Trying to like media: 1324530603681209537
Not liked: 400
Trying to follow: 231820716
Followed: 231820716 #1.
Trying to like media: 1324530595670023386
Not liked: 400
Trying to like media: 1324530595526860600
Not liked: 400
Trying to like media: 1324530587650696369
Not liked: 400

**Comment by MrJur1** [comment]
btw account is not banned, i can like and follow in the app as normal?!

**Comment by PabloStrange** [comment]
for me it looks like your acc got banned, have you tried it again since then?

**Comment by manguszta** [comment]
I have the same issue. My account isn't banned. It didn't work on Saturday, It worked on Sunday, but hasn't work since then. (it's Tuesday)

This happened before some time ago, possibly in the end of June.

**Comment by LevPasha** [comment]
@MrJur1 @manguszta look like ban. Now it is fine?

**Comment by manguszta** [comment]
It is fine now, yes. I wasn't banned.

**Comment by LevPasha** [comment]
@manguszta hm... maybe some internet problem or with instagram.com website...

**Comment by boyboywow** [comment]
I have exactly the same problem, sometimes it's work fine for one like and for the other it's "not liked 400" I have two account and it's exactly the same on the both account.. I am not banned. Really I don't understand

**Comment by manguszta** [comment]
It works fine for me since I do only a maximum of 1800 likes per day. Until then I did around 2200

**Comment by polaroi8d** [comment]
There is other conditions, like how old your account...
