### ISSUE TITLE
bot did't tell me anything

### ISSUE THREAD

**Issue by manumanu2000** [LevPasha/instabot.py#17]
I have followed the guide, at the end of file i have added that code (the * are for privacy):
`bot = InstaBot('****', '***',
               like_per_day=1000,
               media_max_like=10,
               media_min_like=0,
               tag_list = ['cat', 'car', 'dog'],
               max_like_for_one_tag=5,
               log_mod = 0)
		bot.follow(*********)
		bot.auto_mod()`
When i start the bot by console i get no logs and the bot don't work
![powershell](https://cloud.githubusercontent.com/assets/13768863/13533021/cc900190-e22e-11e5-8ac3-7926f52cd102.PNG)

**Comment by LevPasha** [comment]
Hi! It is strange. Try delete `bot.follow(*********)`. If don't work - show my screenshot (without log an pwd), what you write.

**Comment by manumanu2000** [comment]
Hi, thank you for your help, i have tried to delete bot.follow(*********) but It does not work the same.
This is the screenshot by notepad++ text editor. (i have replaced the login and password whit random words
![catturua](https://cloud.githubusercontent.com/assets/13768863/13547739/14431f86-e2de-11e5-9e4c-29ef4bc3c073.PNG)

**Comment by yohn89** [comment]
@manumanu2000 
You put that code (line328~335) in  a wrong location.
Put it in an new python file or removing the indentation

**Comment by LevPasha** [comment]
@manumanu2000 you should learn python syntax. Correct code is:
![14431f86-e2de-11e5-9e4c-29ef4bc3c073](https://cloud.githubusercontent.com/assets/9821835/13631318/04199bc0-e5f5-11e5-8b64-ab68b54809df.PNG)

**Comment by manumanu2000** [comment]
@LevPasha
Thank you for your help, yes i'm stupid and i forget the python syntax.
The bot work perfectly, you did a very great job.

**Comment by LevPasha** [comment]
@manumanu2000 glad for you! Try new version!
