### ISSUE TITLE
Syntax error line 6

### ISSUE THREAD

**Issue by 990sebas** [LevPasha/instabot.py#173]
Whenever I try running the example.py this happens. Why???
Im really new to programming so probably its a easy thing to solve, thanks!

MacBook-Pro-de-Sebastian:instabot.py-master Sebas$ python example.py
  File "example.py", line 6
    bot = InstaBot(login=“********”, password=“*********”,
                         ^
SyntaxError: invalid syntax

**Comment by polaroi8d** [comment]
Im never used mac but, you have tried with `python3 example.py` ? 

Here is the good syntax of the InstaBot :arrow_heading_down:
```
bot = InstaBot(login="my_username", password="my_password",
               like_per_day=1000,
               comments_per_day=0,
               tag_list=['follow4follow', 'f4f', 'cute'],
               max_like_for_one_tag=50,
               follow_per_day=150,
               follow_time=5*60*60,
               unfollow_per_day=150,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0)
```

**Comment by felipeasf** [comment]
I have the same problem, even using python3 example.py.

Any suggestions?

**Comment by 990sebas** [comment]
Im using this syntax  ⤵️

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from instabot import InstaBot

bot = InstaBot(login=“*******”, password=“*******”,
               like_per_day=900,
               comments_per_day=0,
               tag_list=[‘hypebeast’, ‘boost’, ‘yeezy’],
               max_like_for_one_tag=50,
               follow_per_day=150,
               follow_time=5*60*60,
               unfollow_per_day=150,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0)

BUT IT Still tells me syntax error :(  ⤵️

MacBook-Pro-de-Sebastian:instabot.py-master Sebas$ python example.py
File "example.py", line 6
bot = InstaBot(login=“*****”, password=“******”,
^
SyntaxError: invalid syntax
Any tips or idea of what is happening?
Thanks!

**Comment by LevPasha** [comment]
Read about python sintaxis.
