### ISSUE TITLE
Use a sqlite to trace likes, comments and logs

### ISSUE THREAD

**Issue by maxdid** [LevPasha/instabot.py#174]
Hi I'm trying to use a db to avoid more comments on a post, equal comments for different media for one user and so on.
A question: how many media id the function "get_media_id_by_tag" fetch at a time?
Thanks

**Comment by polaroi8d** [comment]
Uhh maybe @LevPasha know the answer.

**Comment by LevPasha** [comment]
@maxdid hi! Debug request answer, or you can go to instagram.com and explore media by tag (and calculate picture). This count can change, and i don't know current value.
