### ISSUE TITLE
Comments not working!!!!

### ISSUE THREAD

**Issue by drewhga** [LevPasha/instabot.py#179]
Am new to python and I really love your work. I need help getting the bot to post comments onto pictures with the tags listed in the tag_list. I tried editing the instabot.py file to post comments not randomly but specifically like ' Follow back' which I found generates more followers. It works fine for about the first 15 follows then it abruptly stops with an error which I think sums up to ::: error_value= no json object can be decoded. Your help will be much appreciated

**Comment by drewhga** [comment]
@LevPasha

**Comment by h-2-0** [comment]
I think if you tell us first what you edited in the instabot.py we can be of better help.

**Comment by drewhga** [comment]
well I couldn't get the bot to post my comments on posts instead it was posting random comments like 'This snapshot is glorious', 'This photo is cool' etc. So I edited the portion below
  def generate_comment(self):
        c_list = list(itertools.product(
                                    ["this", "the", "your"],
                                    ["photo", "picture", "pic", "shot", "snapshot"],
                                    ["is", "looks", "feels", "is really"],
                                    ["great", "super", "good", "very good",
                                    "good", "wow", "WOW", "cool",
                                    "GREAT", "magnificent", "magical", "very cool",
                                    "stylish", "so stylish", "beautiful",
                                    "so beautiful", "so stylish", "so professional",
                                    "lovely", "so lovely", "very lovely",
                                    "glorious", "so glorious", "very glorious",
                                    "adorable", "excellent", "amazing"],
                                    [".", "..", "...", "!", "!!", "!!!"]))

        repl = [("  ", " "), (" .", "."), (" !", "!")]
        res = " ".join(random.choice(c_list))
        for s, r in repl:
            res = res.replace(s, r)
        return res.capitalize()

to

def generate_comment(self):
        c_list = list(itertools.product(
            ["cool!"],
            ["but"],
            ["follow"],
            ["back"],
            ["please"]))

        repl = [("  ", " "), (" .", "."), (" !", "!")]
        res = " ".join(random.choice(c_list))
        for s, r in repl:
            res = res.replace(s, r)
        return res.capitalize()

It works fine for a while then out of nowhere it displays an error and closes

**Comment by drewhga** [comment]
@h-2-0

**Comment by h-2-0** [comment]
Please post full traceback error

**Comment by drewhga** [comment]
![screenshot_2016-09-07-15-12-31](https://cloud.githubusercontent.com/assets/22053531/18329341/7d096b0a-7542-11e6-9ae7-f015fc839ffa.png)

This might help.
I ran it on QPython for android

**Comment by LevPasha** [comment]
@drewhga you can write like this:
```python
    def generate_comment(self):
        return "cool! but follow back please"
```

**Comment by drewhga** [comment]
👍👍👍
Thanks a lot. Its working now

**Comment by drewhga** [comment]
Sorry for reopening it but I needed help.

Is there anyway to get the bot to delete the comments sometime after posting?

**Comment by LevPasha** [comment]
@drewhga there is no ready function for this, but it is real.

**Comment by drewhga** [comment]
Thanks, but I'd appreciate it if you could try to obtain one for me. Thanks in advance
