### ISSUE TITLE
Not getting media ID

### ISSUE THREAD

**Issue by epsyon** [LevPasha/instabot.py#180]
Hi guys, anybody experiencing the same issue?
Been running the bot for like 15 minutes, and only got 2 media IDs to like. It just keeps searching for media as shown... I can assure the tags I used are very popular ones, so that shouldn't be a problem at all.

> Instabot v1.0.1 started at 07.09.2016 14:00:
> 
> Trying to login as XXX...
> 
> XXX login success!
> Get media id by tag: tag1
> Trying to follow: XXX
> Followed: XXX #1.
> Get media id by tag: tag2
> Trying to like media: XXX
> Liked: XXX. Like #1.
> Get media id by tag: tag3
> Get media id by tag: tag3
> Get media id by tag: tag4
> Get media id by tag: tag2
> Trying to like media: XXX
> Liked: XXX. Like #2.
> Get media id by tag: tag4
> Get media id by tag: tag4
> Get media id by tag: tag5
> Get media id by tag: tag6
> Get media id by tag: tag3
> Get media id by tag: tag7
> Get media id by tag: tag4
> Get media id by tag: tag5

This is what I have in my configuration file:
```
from instabot import InstaBot

bot = InstaBot(login="XXX", password="XXX",
               like_per_day=1000,
	       media_max_like = 200,
	       media_min_like = 15,
               comments_per_day=0,
               tag_list=['tag1', 'tag2', 'tag3', 'tag4', 'tag5, 'tag6', 'tag7' ,'tag8', 'tag9', 'tag10', 'tag11' , 'tag12', 'tag13'],
               max_like_for_one_tag=50,
               follow_per_day=30,
               follow_time=5*60*60,
               unfollow_per_day=30,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0)

bot.new_auto_mod()
```

**Comment by h-2-0** [comment]
It appears this happens when tags have hidden posts. Double check your tags on Instagram. Hidden posts are out of sight because users reported them (perhaps of their sexual/spammy nature). All these means you are being shown only popular posts but no recent ones related to the tag (which I guess are the ones Instabot likes).

**Comment by drewhga** [comment]
Any help on how to get the bot to comment?. @h-2-0

**Comment by epsyon** [comment]
That's weird, as all tags are about safe content. 
How can we arrange that then? Something needs to be fixed 🤔

**Comment by h-2-0** [comment]
@epsyon 

I just started playing with the bot. And you are right. Even the cats tag isn't getting any media_id using the new_auto_mod().

**Comment by h-2-0** [comment]
@epsyon

I started playing with my bot's settings and found that the culprit was media_max_like. I set it to 0 and it started working.

**Comment by krs92** [comment]
Change  media_max_like and media_min_like to Zero.

**Comment by LevPasha** [comment]
@krs92 right answer!
