### ISSUE TITLE
Prevent to comment own photo

### ISSUE THREAD

**Issue by phiwut** [LevPasha/instabot.py#183]
Is there a way to prevent that the bot doesn't comment under my own photo?

**Comment by LevPasha** [comment]
@phiwut ahaha, it is funny! Look like you have split personality and talk with yourself)

**Comment by phiwut** [comment]
I meant that the bot doesn't like pictures from the account it's logged in ;)

**Comment by drewhga** [comment]
I think the resolved that issue in the latest commit @phiwut. You should crosscheck it and see
