### ISSUE TITLE
Login error! Check your login data!

### ISSUE THREAD

**Issue by crashwins** [LevPasha/instabot.py#187]
I got this to work and then the above :( Any idea what's happening? I tried logging in/out of IG, but still no success. Was loving this months ago, but had turned it off for a bit! Thanks for all your hard work @LevPasha 

Also - I was just using the example.py, nothing fancy....

**Comment by Sylrelo** [comment]
If you have a backslash (\\) in your password, you need to double it.
Exemple : SuperPassword\o **=>** SuperPassword\\\o

**Comment by crashwins** [comment]
Thanks - no backlash in my PW. Any other ideas? Very weird that it worked and then it stopped...I noticed when I used Robolike once that it wouldn't work until I signed in/out of IG

**Comment by polaroi8d** [comment]
@crashwins if your pass and username in the `example.py` file, its enough for the bot.

**Comment by crashwins** [comment]
Awesome - thanks. Got it working. Any suggestions on keeping it running with my iMac? Apparently stops running during sleep...LittleSnitch?

**Comment by polaroi8d** [comment]
I cant help with iMac, i never used it.

**Comment by peerdenhoed** [comment]
How did you fix it i have the same problem

**Comment by virginsince1997** [comment]
Login into your account with the Instagram app , to verify ,,and also check
your password.. Case sensitive..

**Comment by peerdenhoed** [comment]
Can you explain what you did to fix it? i have the same problem :(
