### ISSUE TITLE
Бот отписывается от аккаунтов, на которые не подписывался

### ISSUE THREAD

**Issue by ierogliph** [LevPasha/instabot.py#189]
Привет. Как реализован unfollow? Бот заводит список аккаунтов, на которые подписался сам и описывается только от них? Мне вчера написало несколько друзей, от которых я, как оказалось, отписался. Но это произошло во время работы бота.
Конфиг стандартный:

```
bot = InstaBot(login="...", password="...",
               like_per_day=2000,
               comments_per_day=0,
               tag_list=[...],
               max_like_for_one_tag=50,
               media_max_like=10,
               media_min_like=0,
               follow_per_day=300,
               follow_time=60*60,
               unfollow_per_day=300,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0)

bot.new_auto_mod()
```

**Comment by LevPasha** [comment]
@ierogliph хм... может быть бот прошел по твои друзьям, "добавил их" (хотя они уже были), а потом удалил.
Нет никакой проверки, перед фоловом, друг он тебе или нет.

**Comment by virginsince1997** [comment]
Pasha please I need to talk to you, Am looking for a bot that can like my
instagram feed as well as save data, Images would be disabled, Or is there
a way to disable instagram app images for Android

**Comment by ierogliph** [comment]
При работе он генерит список людей, на которых подписался и не трогает тех, кто был уже?

**Comment by LevPasha** [comment]
@ierogliph да.
