### ISSUE TITLE
Unlike Feature (Help wanted)

### ISSUE THREAD

**Issue by drewhga** [LevPasha/instabot.py#194]
I have the media Id for a particular picture I want the not to like and unlike but 
bot.like('1111111111')
is not working. Ie. The bot doesn't like the picture with the media id.
Same problem also with the unlike feature. 

Thanks in advance for your help.

**Comment by LevPasha** [comment]
Show your code.

**Comment by drewhga** [comment]
import time

from instabot import InstaBot

bot = InstaBot(login="*****", password="**",
               log_mod=0)
    while true:
    bot.like('1340786680814511082')
    bot.unlike('1340786680814511082')
    time.sleep(30)
    
bot.new_auto_mod()

**Comment by LevPasha** [comment]
@drewhga and what do you see in console? bot.like('1340786680814511082') and bot.unlike('1340786680814511082') without dealy can make like-unlike and you don't see result.

**Comment by drewhga** [comment]
So how do  i make a log_string for the like and unlike

**Comment by LevPasha** [comment]
@drewhga add something like print(log_text) to like and unlike functions.

**Comment by drewhga** [comment]
OK thanks
