### ISSUE TITLE
Just unfollow people not following back

### ISSUE THREAD

**Issue by marfert** [LevPasha/instabot.py#199]
Hi,

is it possible to make the bot just unfollow users who don't follow you back after the specified time period (follow_time)?

I think it would be a great addition to make the bot behave more naturally and keep for followers.

Thanks

**Comment by bobduckling221** [comment]
Yes, that would be really cool. I have been trying to figure how to add such an option but keep on failing. I also think it would be cool if the bot could follow and like based on geolocation. If

**Comment by kemong** [comment]
hi dude check my post here : https://github.com/LevPasha/instabot.py/issues/217 
I already solved it and it works nicely to me :)
