### ISSUE TITLE
but

### ISSUE THREAD

**Issue by saymyname89** [LevPasha/instabot.py#2]
SyntaxError: Non-ASCII character '\xd0' in file instabot.py on line 102, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by LevPasha** [comment]
HI!

1) You don't need to change class. You should do like this:
bot = InstaBot('login', 'password')
bot.auto_mod()

2) Error look like your .py file have ANSII encoding. Change .py file encoding to UTF-8.
https://www.python.org/dev/peps/pep-0008/#source-file-encoding

**Comment by saymyname89** [comment]
Sorry mate,
I can't do this. Could you help me writing the code from scrath, please?

**Comment by LevPasha** [comment]
This does't need any code. You just change encoding of file. This can do your code (text) editor. Tape in google change file encoding "your_text_editor". You need change to UTF-8.

**Comment by saymyname89** [comment]
sorry mate, i have made it before writing the last post. still don't working. the same error.

(i have used text edit for mac makinf py file in py with UTF-8 encoding)

**Comment by LevPasha** [comment]
I make come changes for you. Download new version of instabot, save file with utf-8 encoding, and try start it without any log:
bot = InstaBot('login', 'password', log_mod=2)
bot.auto_mod()
Hope it help you! I don't have Mac to try it myself.

**Comment by saymyname89** [comment]
I'm a pain in the ass I know...
listen how I does in order to correct me. It's important for every unexpert users i think:

Once I get the path i open Terminal and type:
python instabot.py

with the new file now it appears this:

Traceback (most recent call last):
  File "instabot.py", line 1, in <module>
    from lxml import html
ImportError: No module named lxml

I'm too noob, I know, but help me...I'm approaching to this new language for just few days

**Comment by LevPasha** [comment]
Look like you need to install lxml module (use pip install). Maybe it is some problem with it on Mac?

**Comment by alvvvvvin** [comment]
@saymyname89 have you tried to install lxml w/ easyinstall? 

(You might need to update xcode)

http://stackoverflow.com/questions/19548011/cannot-install-lxml-on-mac-os-x-10-9

**Comment by saymyname89** [comment]
tried everything...what OS do you suggest guys? I have an old Windows 7 PC. Could Works?
what programs should I use to run python on windows?

**Comment by LevPasha** [comment]
Download new version of instabot.py. You not need lxml now. Instabot.py work on Windows and Linux, i have no Mac to test.

You should use python 3.4 for Windows (and install request lib for python 3.4). Google will help you with this!

**Comment by saymyname89** [comment]
ok 2 questions:
should i use this string?:
pip install SomePackage

nothing happens...i mean maybe after SomePackage there should be something. Can you help me finding the right code?

then...
when everything will be correct and i will undestrand everthing
how can i should use the bot?
should i just log in to IG with a browser (I use firefox) and use the bot or should i modify something inside the .py file?

**Comment by LevPasha** [comment]
For python 2.7 you use `pip install...` For python 3.4 you should use command `pip3 install...` For instabot you need only `pip3 install requests`. You don't need to install lxml.

For use bot you need:
1) Open instabot.py file. 
2) Add to end of file:
```python
bot = InstaBot('your login', 'your password')
bot.auto_mod()
```
3) Save file and run it (console or terminal).
4) If you want to see how bot work (see log in console) write like this:
```python
bot = InstaBot('your login', 'your password', log_mod=0)
bot.auto_mod()
```

**Comment by saymyname89** [comment]
I have used UTF-8
http://it.tinypic.com/r/n6456g/9

Insert the code
http://it.tinypic.com/r/r8ifew/9

this is the result 
http://it.tinypic.com/r/2vd5uhd/9

**Comment by LevPasha** [comment]
Hi!

When you write `python instabot.py` you run it in python 2.7. You should write `python3 instabot.py` - this commans run in python 3+.

**Comment by LevPasha** [comment]
Add instruction:
https://github.com/LevPasha/instabot.py#how-to-install-and-run

**Comment by saymyname89** [comment]
![1](https://cloud.githubusercontent.com/assets/16817153/12641230/b97109d4-c5ae-11e5-893c-9cecfdea4fb0.png)

ok, i think i have almost done here...but what's wrong with me??? lol
I'm sure i have inserted the correct user and pass

**Comment by LevPasha** [comment]
LOL, look like you troll me)))

![1](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRzou72ATIjCBDToyGc34w3K3O7fxH6L0CHTUYaE3S9iOI_0Vbi)

I think you use wrong '. Maybe `? Try to set "!

`bot = InstaBot("user", "pass")`

**Comment by saymyname89** [comment]
ohh thank you dear! it works greatly!!!
