### ISSUE TITLE
Unfollow

### ISSUE THREAD

**Issue by Bossishere** [LevPasha/instabot.py#206]
Can someone help me out with unfollowpub, because unfollowing on this script isn´t really working for me. 
Thank you:)

**Comment by virginsince1997** [comment]
Isn't working for me too

**Comment by drewhga** [comment]
Sorry to be a spoilsport but unfollowpub stopped working on June 1st. 2016
due to instagram's policy update.

**Comment by polaroi8d** [comment]
There is a same issue in #198 Please check the issue list first before you openning a new one, @Bossishere.
