### ISSUE TITLE
traceback error 

### ISSUE THREAD

**Issue by jcovarrubias11** [LevPasha/instabot.py#213]
i keep getting this error of list index out of range
![screen shot 2016-10-07 at 11 49 35 pm](https://cloud.githubusercontent.com/assets/16827937/19211097/82497a2e-8ce9-11e6-9e85-57ad679794f9.png)

**Comment by jcovarrubias11** [comment]
![screen shot 2016-10-07 at 11 56 20 pm](https://cloud.githubusercontent.com/assets/16827937/19211105/aeefef68-8ce9-11e6-920b-a6896d7b7a10.png)

**Comment by casaoui86** [comment]
Hello, 

I have the same error ! how did you fixed ? thanks

**Comment by developer2013** [comment]
i have also the same error for the bot.

**Comment by bobduckling221** [comment]
line 167:  delete [0] after ['nodes'] 
line 157: i think you just delete the whole line. or if that doesnt work delete the self.populate_user_blacklist() 

@developer2013 @casaoui86 @jcovarrubias11

**Comment by developer2013** [comment]
it's working. thanks!

**Comment by jcovarrubias11** [comment]
@bobduckling is right I just deleted line 157 the self.populate.user.blacklist line and the bot worked perfectly.
