### ISSUE TITLE
Add unfollowed users to a blacklist

### ISSUE THREAD

**Issue by alexcheninfo** [LevPasha/instabot.py#215]
An Instagram user left me this comment: "May I ask how many times you're going to keep following me and unfollowing me on a daily basis?" Lol. Is there a way to add unfollowed users to a blacklist?

**Comment by dave240170** [comment]
As in the example below, user blacklist.

bot = InstaBot('login', 'password',
                like_per_day=1000,
                media_max_like=0,
                media_min_like=0,
                follow_per_day=0,
                follow_time=5*60*60,
                unfollow_per_day=0,
                comments_per_day=0,
                tag_list=['cat', 'car', 'dog'],
                tag_blacklist=['rain', 'thunderstorm'],
                user_blacklist={'hellokitty':'', 'hellokitty3':''},
                max_like_for_one_tag = 5,
                unfollow_break_min = 15,
                unfollow_break_max = 30,
                log_mod = 0,
                proxy='')
