### ISSUE TITLE
Hi i improved your bot.

### ISSUE THREAD

**Issue by kemong** [LevPasha/instabot.py#217]
Hi, i modify your script. It now can do these things :
1. Get media (photos/videos) from your own timeline. Put people who like those photo into list. After it puts people into list, it'll check those people profile. It'll make sure that you only follow people with specific profile. E.g : If a person have Follower 2x more than his following, the bot will think that he is a "Selebgram", so it won't follow that account. If a person have following 2x more than his follower, the bot will think that he is a fake account, so it won't follow him. If a person have uploaded media less than 10% of his following (or) his follower number, the bot will think that he is a passive account, so it won't follow him.

2. The bot can unfollow people who don't follow you back. It'll scan medias on your timeline, check the account who upload it. If the person who upload it follow you, the bot will ignore him. But if that person doesn't follow you or no sending any follow request (if your account is private) then it will check that account profile. It'll check whether he is a "Selebgram" / "Fake Account" / "Passive Account". If the bot think that he is not a normal account, it will just sending unfollow request for that account. But if the bot thinks that he is a normal person, it will scan his medias. The bot will like photos randomly before sending unfollow request for that account as many photos as you want for maximum 12 photos.
IF the photos have like number more than 50, the bot will not like it. Because your like would be insignificant for him/her. You can adjust like number by yourself.

3. While doing the #1 feature, the bot can determine whether a person should be put into your list or not if he has blacklisted name or not. E.g : if a person name is "Maximilian_Art", the bot will reject him, because i make a blacklist which contains *art*...you can make your own blacklist such as : *follow/ *porn/ or everything. So the bot will get best people for you. It make double check before sending follow request to someone. First by checking his/her name, is it contains your blacklisted string? if not it will check is him a Selebgram or Fake Account or Passive Account? if not then the bot will follow him/her. 

4. I make some rules to my bot. On first start the bot will check your own profile. Do you have more follower than following or not? If i have less following than follower number, then I will follow people untill i hit 400 following more than follower. After i hit that number, the bot will begin unfollowing people by executing protocol #2. It will continues to unfollow people until i hit 200 following more than follower number. It will continue to work repeatedly.

Download the file below V

**Comment by rohit366** [comment]
Would love to connect, I just sent you a mail, please check and revert.

**Comment by kemong** [comment]
Hi just extract it buddy, if it doesn't work let me know. Thanks

**Comment by bobduckling221** [comment]
@kemong Just sent you an email too. Would love to see the new added features)

**Comment by kemong** [comment]
Hi just extract it buddy, if it doesn't work let me know. Thanks

**Comment by bobduckling221** [comment]
>>> 
========== RESTART: C:\Users\Desktop\NewInstabot\test.py ==========
Traceback (most recent call last):
  File "C:\Users\Desktop\NewInstabot\test.py", line 4, in <module>
    from instabot import InstaBot
  File "C:\Users\Desktop\NewInstabot\instabot.py", line 428
    print "%i" %(self.is_follower_number)
             ^
SyntaxError: invalid syntax
>>> 

@kemong 

This is what i got

**Comment by kemong** [comment]
Hi, do you have experience with python syntax? I think you can try to 
edit the file instabot.py, replace the "Space" with "Tab" or Tab with 
Space. I'm using Linux and it works. The code is work, it's just 
indentation problem.

**Comment by bobduckling221** [comment]
Ok i changed spaces and tabs, also in line 609: if len(self.media_by_tag)=0: I got rid of the =0. And it started working smoothly. ))

**Comment by kemong** [comment]
@bobduckling221 well i'm happy to hear that bob. Have a great day~

**Comment by bobduckling221** [comment]
Ok sorry for bothering you again but:  Current Index = 4 of 9 medias
Too much liker for this media!!! LC = 59   these keep on popping up. What do they mean.

**Comment by virginsince1997** [comment]
On what line do I change spaces and tabs, Got a syntax error while trying
to run

**Comment by Bossishere** [comment]
Can you send the code here?

**Comment by kemong** [comment]
Ok sorry for that. LC means Likes Count...so if the photo you're going 
to like has Likes Counts more than 50, the bot will not like it. You can 
change the Like Threshold by changing the "if l_c < 50:" with "if l_c < 
XX:" please look a my attachment.

**Comment by kemong** [comment]
HI, if you're windows user, i suggest you to contact Bob, cause i use 
linux and the codes are find. Please ask bob, maybe he can send you his 
modified script that work under Windows. Thank's

**Comment by kemong** [comment]
Just extract it dude. Let me know if it doesn't work..If you're windows 
user, try to contact Bob and ask for modified script. Thank's

**Comment by virginsince1997** [comment]
Please can you send me you're modified Windows script am getting, syntax
error... My email  pikuda42438@gmail.com

**Comment by bobduckling221** [comment]
email is bobduckling123@gmail.com... and i sent modified version for (Windows) to @kemong and @virginsince1997

**Comment by kemong** [comment]
New Instabot : Tested on LinuxMint 17.3 Rosa
[NewInstabot.zip](https://github.com/LevPasha/instabot.py/files/520090/NewInstabot.zip)

New Instabot Mod : Tested on Windows
[Win_modified.zip](https://github.com/LevPasha/instabot.py/files/520099/Win_modified.zip)

**Comment by h-2-0** [comment]
Excellent contribution @kemong !

**Comment by LevPasha** [comment]
@kemong hi! Sound great! Can you make pull request (maybe with all you write in different folder, if it have big problem to intergate it to my bot). Wait it!

**Comment by kemong** [comment]
@h-2-0 Thank's dude !
@LevPasha Done sir ! :)

**Comment by LevPasha** [comment]
Everyone go to test it! https://github.com/LevPasha/instabot.py/pull/218

**Comment by Bossishere** [comment]
unsupported operand type(s) for %: 'NoneType' and 'int'

My ERROR that appears
HELP  pls

**Comment by Redouan29** [comment]
It works great. Nice script

**Comment by Bossishere** [comment]
Its not working for me, I have an account that has more followers than following, it just freezes, PLS help

**Comment by kemong** [comment]
Hi @Bossishere  ...you have to modifiy the instabot.py and test.py to suit you. Or if you want the easy way out, you can first start to follow people using LevPasha instabot.py....and then use my script to unfollow people who don't follow you back. To start unfollow your following edit the test.py and only call new_auto_mod2() without any rules (if following > follower should be deleted) thank's

**Comment by marfert** [comment]
Hi @kemong, thanks for your contribution. Is it possible to keep the bot behavior the same as the original bot and just make it unfollow people that don't follow back?

**Comment by kemong** [comment]
@marfert ah, piece of cake..
here is the original instabot + added unfollow feature. The bot will unfollow based on your recent feed.
Use the example.py
[ori_plus_unfoll.zip](https://github.com/LevPasha/instabot.py/files/522642/ori_plus_unfoll.zip)

maybe u can buy me a cup of coffee haha

**Comment by kemong** [comment]
Hi @marfert this is the original instabot + unfollow feature + profile checker
it works with original example.py
[ori_plus_unfoll.zip](https://github.com/LevPasha/instabot.py/files/522703/ori_plus_unfoll.zip)

**Comment by LevPasha** [comment]
@kemong make new pull (as we talk about)!

**Comment by kemong** [comment]
hai boss @LevPasha  i've upload my work https://github.com/LevPasha/instabot.py/issues/227
everybody may check it and upgrade as soon as posible..and enjoy the new power.... 
cheers :beers: @marfert  @bobduckling221  @rohit366  @virginsince1997  @Bossishere  @h-2-0 @Redouan29

**Comment by devichris** [comment]
> hai boss @LevPasha i've upload my work #227
> everybody may check it and upgrade as soon as posible..and enjoy the new power....
> cheers beers @marfert @bobduckling221 @rohit366 @virginsince1997 @Bossishere @h-2-0 @Redouan29

I know this is an old thread but is there a pull request for this? Im curious to know what the diff is

**Comment by lonestoner001** [comment]
Hello @kemong 
Ran through your codes, but the bot does not detect unfollowers...
Says"trying to unfollow #1:"
Then "Looks like there is nobody to unfollow"
