### ISSUE TITLE
Couldn't find caption - not liking

### ISSUE THREAD

**Issue by Redhead9** [LevPasha/instabot.py#223]
It comments and follows but I must be doing something wrong because it doesn't like anything at all. Some help please?

**Comment by dave240170** [comment]
This was fixed, do you have latest version?

**Comment by Kelvinplam** [comment]
I just updated to the newest version. Having this problem as well.

**Comment by dave240170** [comment]
try this

https://github.com/LevPasha/instabot.py/issues/202

**Comment by Redhead9** [comment]
The code is still up and I just downloaded the master today. I ended up commenting the return false after the except. Thank you though.

**Comment by LevPasha** [comment]
Fix it in last version.
