### ISSUE TITLE
Couldn't find caption - not liking

### ISSUE THREAD

**Issue by epicbrony** [LevPasha/instabot.py#228]
Instabot v1.0.1 started at 13.10.2016 00:27:

Trying to login as blurryshadowz...

blurryshadowz login success!
Completed populating user blacklist with IDs
Get media id by tag: tylerjoseph
Couldn't find caption - not liking
Trying to follow: 3446822026
Followed: 3446822026 #1.
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Get media id by tag: joshduni
Couldn't find caption - not liking
Keep calm - It's your own media ;)
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking

ughhhh problems

**Comment by dave240170** [comment]
https://github.com/LevPasha/instabot.py/issues/202

**Comment by dave240170** [comment]
make line 311 just;

caption = self.media_by_tag[i]['caption']

**Comment by maxdid** [comment]
I downloaded the zip file now and after changed line 311 I still have the same error. My example.py is without any modification except username and password.
Could someone give me a direction where to look at?
Thanks,
   Massimo

**Comment by LevPasha** [comment]
Test last version, i think i fix it.

**Comment by stephencoe** [comment]
The latest version is still doing this

**Comment by LevPasha** [comment]
@stephencoe show me your tag list.

**Comment by stephencoe** [comment]
my test tags: `tag_list=['TonyDaniel', 'DCComics']`

**Comment by LevPasha** [comment]
![image](https://cloud.githubusercontent.com/assets/9821835/19433087/f7a3c772-9467-11e6-9ffb-2b6679a79b6d.png)

**Comment by stephencoe** [comment]
it looks like my problem was with the python version, I updated to python3 and it runs fine. Thanks for following up 👍

**Comment by supa4di** [comment]
Hi, im having the same problem with latest version of program and python 3 :(

**Comment by supa4di** [comment]
also i have edit line 311
