### ISSUE TITLE
Russian tags

### ISSUE THREAD

**Issue by ictek05** [LevPasha/instabot.py#23]
How i can add Russian tags?

**Comment by ictek05** [comment]
utf 8 например

**Comment by shayanb** [comment]
add this on top of your python file
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```

**Comment by LevPasha** [comment]
@ictek05 берешь да пишешь! Если ты питон 3 используешь - файл должен быть в утф-8. Сам использую часть тегов на русском, проблем нет.
