### ISSUE TITLE
AttributeError? (Drops Out Ocassionally) 

### ISSUE THREAD

**Issue by virginsince1997** [LevPasha/instabot.py#230]
Liked: 1360889617801128327. Like #6.
Trying to unfollow #%i:
Traceback (most recent call last):
  File "/storage/emulated/0/org.qpython.qpy/scripts/ultimatebot/example.py", line 55, in <module>
    bot.new_auto_mod()
  File "/storage/emulated/0/org.qpython.qpy/scripts/ultimatebot/instabot.py", line 516, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/storage/emulated/0/org.qpython.qpy/scripts/ultimatebot/instabot.py", line 561, in new_auto_mod_unfollow
    self.auto_unfollow()
AttributeError: InstaBot instance has no attribute 'auto_unfollow'
Trying to unfollow: 21198436
Unfollow: 21198436 #1 of 1.
Pausing for 23 seconds... 1 of 1
Logout: likes - 6, follow - 1, unfollow - 1, comments - 3.
Bot work time: 0:02:26.257923
Logout success!
Exception KeyError: KeyError(-1225720852,) in <module 'threading' from '/data/data/org.qpython.qpy/files/lib/python27.zip/threading.pyo'> ignored

#[QPython] Press enter to exit

**Comment by kemong** [comment]
replace your instabot.py with this [instabot.py.zip](https://github.com/LevPasha/instabot.py/files/530825/instabot.py.zip)

**Comment by LevPasha** [comment]
@kemong plz make pull with "src folder". This is bad idea to give .zip in issues.

**Comment by virginsince1997** [comment]
@kemong, it doesn't reject unfollow
B@@@@@
It just unfollows everyone even if they don't meet requirements for unfollow
