### ISSUE TITLE
Optimum settings for followers?

### ISSUE THREAD

**Issue by chrisgreg** [LevPasha/instabot.py#232]
Just wondering what you guys are using for the settings and how good your results are?

Using the defaults on mode 0 with 600 likes and 150 follow/unfollow a day I get around 30 new ones in around 5-6 hours.

Anyone finding better results?

I don't wanna get banned so I'm not upping it too much - what are you guys finding?

EDIT: Sorry I know this isn't really an issue but I didn't know where else to ask about this

**Comment by kemong** [comment]
Hy @LevPasha 
can we make a facebook group or other chat group so we can ask something to someone or discussing somthing without open new issues? thank's

**Comment by virginsince1997** [comment]
@kemong maybe LINE?

**Comment by drewhga** [comment]
How bout WhatsApp? Or since this is an Instagram bot everyone using it will
definitely be on Instagram so I suggest we use an Instagram group chat

**Comment by LevPasha** [comment]
@chrisgreg all account need different settings. Find best for you.

@kemong @virginsince1997 @drewhga think i have no time to read this chat. But if you create this - add me to. I like Telegram.

**Comment by drewhga** [comment]
I'm creating the Instagram group chat now. DM me @drew._hga

**Comment by arsischeon** [comment]
@drewhga Great idea. I just sent a DM. Telegram would be also good if @LevPasha can join.

**Comment by TTAAEELL** [comment]
Telegram group will be so good.

**Comment by TTAAEELL** [comment]
I've created a group on Telegram. Here is the link and you can join:

https://telegram.me/joinchat/BYVeSwpAYa2gSPzEFRxFsg

**Comment by LevPasha** [comment]
Ok, join on TG - https://telegram.me/joinchat/DYKH-wdXpfmQCdcJLaV48Q

**Comment by davisonio** [comment]
I've also created a Facebook group since lots of people are on Facebook: https://www.facebook.com/groups/instabot/

**Comment by drewhga** [comment]
I found that using hash tags affiliated to "gain trains" produce lots of followers. The gain trains are instagram posts which urge people to follow linkers and commenters of  a particular post and also repost so generally those who repost are more likely to follow back as compared to #follow4follow which is a generic tag provided by all tag4likes apps.
Example of these tags are #gaintrain #jaygaintrain #figure8gaintrain

**Comment by chrisgreg** [comment]
@drewhga so you're saying just plug these sorts of tags into the hashtags that the bot searches for will result in more followers?

**Comment by drewhga** [comment]
Yes I'm saying those who use that hash tag have a higher probability of
following back

**Comment by TTAAEELL** [comment]
@drewhga Using these hashtags for following and liking or adding them to posts?

BTW, I think non-related followers worth nothing.

**Comment by drewhga** [comment]
OK then if related followers are what you want then I would not recommend
this
