### ISSUE TITLE
modes

### ISSUE THREAD

**Issue by bobduckling221** [LevPasha/instabot.py#234]
Could someone please explain the modes... And how they work 0-5. I don't really understand.
Thanks ))

**Comment by LevPasha** [comment]
@bobduckling221 me to) use mode = 0.

**Comment by maxdid** [comment]
:) Yes!
I'm testing last version and the "caption" error has gone!! Thanks a lot

**Comment by bobduckling221** [comment]
what about the other modes... Im a bit confused on how they work

**Comment by maxdid** [comment]
Here you can find a description:
[https://github.com/LevPasha/instabot.py/pull/229]

**Comment by LevPasha** [comment]
I test only 0.

Here is a little bit guide of the modes :
"# MODE 0 = ORIGINAL MODE BY LEVPASHA

Like photos based on tag you've provided, follow the people who upload it, and make comments
"## MODE 1 = MODIFIED MODE BY KEMONG

The bot will figure out, do you have more following than follower? if yes then start unfollowing people who doesn't follow you back. The opposite the bot will start to find people who like photos on your feed, put them into a list. Check those people profile, name, and make sure you follow people with higher chance of getting follow back before sending a follow request.
"### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK

Same as method one plus you unfollow people who don't follow you back
"#### MODE 3 = MODIFIED MODE : UNFOLLOW PEOPLE WHO DON'T FOLLOW BACK

The bot will try to open your recent feed. It will check the account who upload the photo, if the account follow you, the bot will ignore him/her. If the account don't follow you, the bot will left him/her a few like on his/her photos before sending unfollow request.
"##### MODE 4 = MODIFIED MODE : FOLLOW PEOPLE BASED ON RECENT FEED

Eg. Mozart upload a photo, his photo is in your feed. The bot will open Mozart profile. From mozart profile, the bot will choose randomly one of his photo. The bot find out that Da Vinci likes Mozart Photo, so the bot put Da Vinci ID into list. Before sending follow request to Da Vinci, the bot will make a simple check whether Da Vinci worth to follow or not. If Da Vinci only a fake account, the bot will kick his ass from the list.
"###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY

That's it unfollow everybody

**Comment by virginsince1997** [comment]
@pasha it's, most of the modes are buggy it, unfollows people who follows
you,

**Comment by bobduckling221** [comment]
@maxdid @kemong @LevPasha Thanks!
