### ISSUE TITLE
Followers and Following lists

### ISSUE THREAD

**Issue by Maxthebo** [LevPasha/instabot.py#235]
Hi there... Did u guys find a new way to get the followers list of any user?

https://data.ink361.com/v1/users/ig-%s/followed-by
https://www.instagram.com/%s/followers/

both links doesnt work

**Comment by kemong** [comment]
open up someone profile, open one of their photos, look at the people who like it. There, you will get someone's follower User ID and you can send follow request to them. But you can try to use "LevPasha's" InstagramAPI... i never try using it, though....

**Comment by LevPasha** [comment]
@Maxthebo use API - https://github.com/LevPasha/Instagram-API-python
