### ISSUE TITLE
Just unfollow account follow by the bot

### ISSUE THREAD

**Issue by Shiftiing** [LevPasha/instabot.py#239]
Hey,

I just download your new bot with different version.
I test it but I have a question.
How can I configure the bot for just unfollow instagram account who are follow by the bot after a 24 hours for example ?

Thanks for your work :)

**Comment by kemong** [comment]
Use bot in mode 0.

**Comment by virginsince1997** [comment]
I get JSON error while using the unfollow in mode 0

**Comment by kemong** [comment]
mode 0 is unmodified mode...what error did you get?

**Comment by davisonio** [comment]
Would be good to have the feature of a non-volatile bot. I tried the only unfollow mode but it didn't work.
