### ISSUE TITLE
Making a followbot.

### ISSUE THREAD

**Issue by 179skr** [LevPasha/instabot.py#24]
Hi, i am trying to make a follow unfollow bot but i am struggling to make it. basically i want the bot to.

Get certain user followers in a list.
Follow 100 Users Per Hour
UnFollow Followed User after 24 Hours.

Rinse and repeat without following the same user again.

Anyway of making this? I am really struggling to make it. I cant get it to follow anyone.

**Comment by LevPasha** [comment]
Hi @179skr! New version of my bot can do it. It have bad readme now, but i change it in future.
I think 100 follow in hour is too much (they can ban you)!

**Comment by 179skr** [comment]
Could you show me how to code it to follow another users followers?...100 is way too much i was thinking more like 20-40 people maybe.

**Comment by Tonners15** [comment]
Can this scrip loop likes? mine only Likes 1 and then it stops?
