### ISSUE TITLE
How to use comments?

### ISSUE THREAD

**Issue by dannyvoid** [LevPasha/instabot.py#241]
I tried looking at the readme, and the example. I'm lost on how to make the bot comment.

**Comment by polaroi8d** [comment]
You need to edit the src/instabot.py file in line 584, here is the link  [>>](https://github.com/LevPasha/instabot.py/blob/master/src/instabot.py#L584)

Its randomized. Take look at the code, and if you have any other question, feel free to ask :)

**Comment by dannyvoid** [comment]
Thank you! This is exactly what I needed. Is there a recommended "comments per day" as to avoid being banned?

**Comment by polaroi8d** [comment]
In the README.md there is the 'example' values whic is highly recmonended so yes, 50.
