### ISSUE TITLE
Rate Limits?

### ISSUE THREAD

**Issue by ncs5183** [LevPasha/instabot.py#247]
This may be a repeat issue, but has anyone "optimized" this process and figured out where the soft spot is for how many you can follow per day and unfollow without getting banned?

**Comment by 179skr** [comment]
Nope, lol i keep getting limited.

**Comment by ncs5183** [comment]
What are your settings at?

**Comment by TTAAEELL** [comment]
I'm using the default values and they are fine.

**Comment by ncs5183** [comment]
What kind of follows are you getting per day?

**Comment by polaroi8d** [comment]
@ncs5183 there is an issue #245, where you can ask questions like this. Please stop openning dumb issues.
