### ISSUE TITLE
Preventing bot from following unfollowed users (includes sample code)

### ISSUE THREAD

**Issue by alexcheninfo** [LevPasha/instabot.py#248]
Recently, I started to seeing comments like this one in my accounts:

> May I ask how many times you're going to keep following me and unfollowing me on a daily basis ?

What happen is, the bot will follow and unfollow the same users again and again.

I'm not a Python programmer, but I asked around for help, and I came up with these additions:

```
self.unfollowed_users = {}
     with open("unfollowed_users.json", "r") as fp:
     self.unfollowed_users = json.load(fp)

def new_auto_mod_follow(self):
     # some code
     if self.media_by_tag[0]["owner"]["id"] in unfollowed_users['unfollowed_users']:
         self.write_log("You've unfollowed this user in the past!")
         return

def follow(self, user_id):
     # some code
     with open("unfollowed_users.json", "r") as fp:
         data = json.load(fp)
         self.unfollowed_users = data
         data["unfollowed_users"].append(user_id)
     with open("unfollowed_users.json", "w") as fp:
          json.dump(data, fp)
```

Do you guys want me to create a pull request? Or you think this shouldn't be a core feature?

(The reason, I didn't use `user_blacklist` is because I don't know how to get the name of the user from inside the bot.)

**Comment by polaroi8d** [comment]
There is an issue for this. #245
