### ISSUE TITLE
Liking by Location

### ISSUE THREAD

**Issue by Faykai** [LevPasha/instabot.py#249]
Hi Guys,
I saw somewhere here around that someone talked about liking by location by adding "l:12345678",
to the TagList .
First, I can't find it anymore here.
Second, somebody know if it's works and how to run this option ?

It'll help a lot to some people who are running this code for branding .

TIA !

**Comment by Faykai** [comment]
found the post about that but couldn't understand if it's working and how 
https://github.com/LevPasha/instabot.py/pull/221

**Comment by polaroi8d** [comment]
There is an issue, for these questions. #245
