### ISSUE TITLE
Login Error! Connection Error!

### ISSUE THREAD

**Issue by 179skr** [LevPasha/instabot.py#25]
I keep getting a login error! Connection error. I dont know what i am doing wrong.

**Comment by LevPasha** [comment]
@179skr show screenshot with error.

**Comment by 179skr** [comment]
See screenshot below. I am typing the correct login and password and i have installed everything properly.

https://cloud.githubusercontent.com/assets/13633602/13746131/bfc47168-e9e9-11e5-9e03-49920925fc69.png

**Comment by LevPasha** [comment]
@179skr it is mean that you have some connection error when bot try connect to `https://www.instagram.com/accounts/login/ajax/`. Check your connection!

**Comment by 179skr** [comment]
Managed to fix it

**Comment by elmaster999** [comment]
how u managed to fix it?
