### ISSUE TITLE
How come 1000 Likes Max in a day

### ISSUE THREAD

**Issue by klikendish1** [LevPasha/instabot.py#250]
Hi,
I was wondering how come the recommended like limit per day is 1000,
when the instagram one is 350 per hour (8400 per day)

Thanks!

Also is there a way to make it per hour then?

Just trying to like the most posts possible without ban

**Comment by polaroi8d** [comment]
There is an issue, for these questions. #245

**Comment by rzorrudy** [comment]
any answers?

**Comment by dimisdas** [comment]
@rzorrudy necro posting?
