### ISSUE TITLE
Like only 1 photo

### ISSUE THREAD

**Issue by AlanFarley** [LevPasha/instabot.py#259]
Hi,

When I run it, it makes a search by tags, but when first finds he likes and then not like any more.
How to solve?

>Instabot v1.0.1 started at 05.11.2016 12:35:

>Trying to login as aftestes...

>aftestes login success!
>Completed populating user blacklist with IDs

>Get media id by tag: afteste5
>Get media id by tag: afteste7
>Trying to like media: 1376907312388564100
>Liked: 1376907312388564100. Like #1.
>Get media id by tag: afteste5
>Get media id by tag: afteste7

Stopped here, no more scans.

Sorry bad english.

**Comment by antoniotrento** [comment]
Have you used only one tag into the config file? I was installed 4 hours ago and works well for likes and follow

**Comment by kemong** [comment]
Are you sure there are a lot of people on this planet using that hashtag???
