### ISSUE TITLE
при запуске ничего не проиходит

### ISSUE THREAD

**Issue by mugukamil** [LevPasha/instabot.py#26]
ввел свои данные в файл example, при запуске ничего не проиходит...

<img width="360" alt="screenshot 2016-03-15 15 00 15" src="https://cloud.githubusercontent.com/assets/4193470/13777054/b5fa85fc-eabe-11e5-8e11-01bdd98eaa87.png">

**Comment by LevPasha** [comment]
@mugukamil привет, запускать нужно сам файл example.py

**Comment by mugukamil** [comment]
@LevPasha а понял все гуд.
