### ISSUE TITLE
How add comments on test.py

### ISSUE THREAD

**Issue by antoniotrento** [LevPasha/instabot.py#260]
The script works but now I'm looking to understand how to auto comment some pics...

Only add the parameters related to comment into the config.py file?

**Comment by Killerherts** [comment]
I'm also wondering this

**Comment by antoniotrento** [comment]
I think they was saved in another file into src folder but I don't know were, because the comments works, and well, however, said as he prefers the bot with an already predefined list that I would change. Now I do not have time to comb through as soon as I placed the solution (sorry for bad english)

**Comment by Killerherts** [comment]
Yeah peaked throung found no list in source

**Comment by flasheye** [comment]
Look for "generate_comment()" in "instabot.py":

["this", "the", "your"],
["photo", "picture", "pic", "shot"],
["is", "looks"],
["great", "good", "very good"]
[".", "..", "...", "!", "!!", "!!!"]
