### ISSUE TITLE
exemple.py won't open

### ISSUE THREAD

**Issue by tiagokotryk** [LevPasha/instabot.py#263]
The file exemple.py is not working. When I open it, a window appears very quickly and close it self. How do I fix it?
Also, how do I install Python lib requests? It says to run command "pip3 install requests", but where? cmd? powershell?

Please, help! :(

**Comment by virginsince1997** [comment]
Use python 2.7,
To install urllib3,  pip install urllib3
Make sure you included your details in the example.py

**Comment by virginsince1997** [comment]
In Cmd preferably
Make sure you type "python" in cmd before preceding to install any module

**Comment by tiagokotryk** [comment]
do you have a "step by step" for the installation of urllib3 and pip install urllib3?

In the cmd the error I found is:

>>> pip3 install requests
  File "<stdin>", line 1
    pip3 install requests
               ^
SyntaxError: invalid syntax

**Comment by drewhga** [comment]
You need to install pip first.
Alternatively go to the official github repository of requests
https://github.com/kennethreitz/requests
Clone requests.
Unzip the downloaded file and then copy just the "requests" folder in the
unzipped file.
Go to the folder in which you installed Python, normally C:\Python34 and
then paste it in the "Lib" folder and you're good to go.

**Comment by tiagokotryk** [comment]
Thank you friend. Could you also help me to run the exemple.py? I already did the needed editions inside the file.
