### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGQUIT'

### ISSUE THREAD

**Issue by lgs777** [LevPasha/instabot.py#27]
when I was run to example. this massage appeared..
how can I solve it??

>>> 
 RESTART: C:\Users\lgs777\Downloads\instabot.py-master\instabot.py-master\example.py 
Insta Bot v1.0 start at 17.03.2016 02:39:
Try to login by paipai404...
Look like login by paipai404 succes!
Traceback (most recent call last):
  File "C:\Users\lgs777\Downloads\instabot.py-master\instabot.py-master\example.py", line 11, in <module>
    log_mod=0)
  File "C:\Users\lgs777\Downloads\instabot.py-master\instabot.py-master\instabot.py", line 133, in __init__
    signal.signal(signal.SIGQUIT, self.cleanup)
AttributeError: 'module' object has no attribute 'SIGQUIT'
>>>

**Comment by 179skr** [comment]
What code are you using? Could you show your code?

**Comment by lgs777** [comment]
@179skr  

from instabot import InstaBot

bot = InstaBot(login="paipai404", password="dl******",
               like_per_day=1000,
               max_like_for_one_tag=5,
               follow_per_day=150,
               follow_time=5*60*60,
               unfollow_per_day=150,
               comments_per_day=50,
               tag_list=['girl', 'car', 'cat'],
               log_mod=0)

bot.new_auto_mod()

I am using example.py

**Comment by LevPasha** [comment]
@lgs777 strange, it's work fine when i test. Make commit fot you b47ce853b817560feece4c03dadd760a375ca752
