### ISSUE TITLE
couldn't find caption problem on instabot

### ISSUE THREAD

**Issue by supa4di** [LevPasha/instabot.py#280]
Python 3, change in skript nothing but tags

**Comment by slavache** [comment]
hi! i dont understand, dont use tags in script? or not?

**Comment by supa4di** [comment]
No, bot can't like pictures, it writes me couldn't find caption- not liking

**Comment by supa4di** [comment]
Instabot v1.0.1 started at 13.10.2016 00:27:

Trying to login as blurryshadowz...

blurryshadowz login success!
Completed populating user blacklist with IDs
Get media id by tag: tylerjoseph
Couldn't find caption - not liking
Trying to follow: 3446822026
Followed: 3446822026 #1.
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Get media id by tag: joshduni
Couldn't find caption - not liking
Keep calm - It's your own media ;)
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking


Like this (took it from previous issue which is closed already)

**Comment by slavache** [comment]
i have same problem and write about this bug in the neighboring post.

**Comment by supa4di** [comment]
Yes i have read issues abot that so i have the latest version also i have python 3 and edited line 311 try to remove try\exept. So idk why it isnt working for me.

**Comment by bobduckling221** [comment]
Hello, Everyone. I would suggest going to line **_348_** in instabot.py. @supa4di  @slavache 
But the not liking is not a problem. I mean you arent liking a photo every second. But if you are unoyed by that just edit line **_348_**
