### ISSUE TITLE
Looping Likes

### ISSUE THREAD

**Issue by Tonners15** [LevPasha/instabot.py#29]
Can this script loop likes? continue? mine only does one like and it stops. 

http://tinypic.com/r/2z7mtly/9

then it stops

**Comment by rl421403** [comment]
Post your code here.

**Comment by Tonners15** [comment]
Hey nvm it's working, it's just taking time between each like, Is there a way to change the time between likes maybe?

**Comment by rl421403** [comment]
Yeh, it's been explained in readme. You can change `like_per_day=1000` value to reduce time between likes. For like every 2 minutes use `like_per_day=720`.

**Remember**, If you like aggressively then Instagram may ban your account.

**Comment by Tonners15** [comment]
Okay, yeah let's not abuse it haha. I also noticed sometimes hashtags skip. Ever seen that?

**Comment by Tonners15** [comment]
Get media id by tag: fashion
Get media id by tag: makeup
Get media id by tag: fashion
Get media id by tag: fashion
Get media id by tag: hype
Get media id by tag: fashionpost
Get media id by tag: fashion
Get media id by tag: hair
Get media id by tag: fashion

it would keep skipping

**Comment by LevPasha** [comment]
@Tonners15 you find answer to your problem? Write it her, for other users!

**Comment by Tonners15** [comment]
it does skip sometimes but it works great really!

**Comment by LevPasha** [comment]
@Tonners15 look to `media_max_like=10, media_min_like=0` parametrs.

**Comment by Tonners15** [comment]
how do you change the timing between each like?

**Comment by LevPasha** [comment]
@Tonners15  look what @rl421403 comment 2 days ago...
