### ISSUE TITLE
Use this url to speed up user info lookup by username !!!

### ISSUE THREAD

**Issue by ArtemBernatskyy** [LevPasha/instabot.py#297]
https://www.instagram.com/therock/?__a=1

**Comment by ArtemBernatskyy** [comment]
Imho it is better than parsing it via requests text find

**Comment by barneyvaughan** [comment]
Any indicator on how to use the cursor to retrieve the full list through that link?

**Comment by ArtemBernatskyy** [comment]
@barneyvaughan  and one more url https://www.instagram.com/p/BNcPbuvhvT0/?tagged=design&__a=1  
This one resolves user data via 'user code' which you can get from  parsing any post

**Comment by ArtemBernatskyy** [comment]
@barneyvaughan i don't understand 'Any indicator on how to use the cursor to retrieve the full list through that link?' please rephrase

**Comment by ArtemBernatskyy** [comment]
it is a part of much general problem

**Comment by barneyvaughan** [comment]
I meant any way to prevent it just bringing in the first 12 and just bring in all of the media instead. 

I see there is a next_page_id value but I'm not sure how it works.

It's okay I'll have a crack at it myself
