### ISSUE TITLE
Works well! thanks! What about the follow?

### ISSUE THREAD

**Issue by taktikal17** [LevPasha/instabot.py#3]
Hi LevPasha, 

Congrats'! it works like a charm! 
Is the option follow ready to use?

Thanks!

**Comment by LevPasha** [comment]
Hi! Glad that everything worke! 

I don't need follow for me, but will write it for you. I think it take few days.

**Comment by LevPasha** [comment]
@taktikal17 it is ready in manual mode `follow()`: 543e57ca0f66312de02e7691edf6e565223e0017
In future i will rewrite `auto_mod()` to make auto likes, comments, follow and unfollow.

**Comment by taktikal17** [comment]
Hey @LevPasha !

Thanks, it could be great, if you can input one user name, and the script will follow all these followers. At the same time, it writes the user_id of each new followers on a file in order to unfollow him later and to do again this loop.

What do you think about it?


Currently, my script gets the user_id and this number of followers and followings when I input an user name. I need to figure out how to get the follower list.

We keep in touch!

**Comment by LevPasha** [comment]
@taktikal17 i don't sure this is first need functional, maybe later, or you can fork it yourself ))

**Comment by taktikal17** [comment]
@LevPasha yes sure, it could be the final product. It can be achievable with the hashtags, something similar to the Like. Follow people who post on the selected hashtags. 
Nevertheless follow people based on a the follower list of an user can be harder, we don't have access to the follower list on the website, we have only access on websta and the app.. 

Have a good one!

**Comment by taktikal17** [comment]
Hi @LevPasha,

I am testing the script this week. 
I added a line to avoid to like undesirable contents.


`if (self.media_by_tag[i]['likes']['count'] < \
                        self.less_than_likes and self.media_by_tag[i]['likes']['count'] > \
                        self.more_than_likes ):
                        log_string = "Try to comment media: %s" %\
                            (self.media_by_tag[i]['id'])`

In average the undesirable contents have less than 7 likes. I like less posts per minutes ( it takes more time to fit the specifications) but I don't need to check the posts liked.

Have a good one!

I am going to test your new script tonight!! 
Thanks!

**Comment by LevPasha** [comment]
I don't shure that less than 7 likes mean, that media is undesirable. Maybe media just added, and followers have no time to like. But it is good function - add it in next commit. THX!

**Comment by LevPasha** [comment]
Change var names (`more_than_likes` to `media_max_like=10`, `less_than_likes ` to `media_min_like=0`) eea1439b8463d01da8327f14b509cd2fec8bf1f2

**Comment by taktikal17** [comment]
Hey @LevPasha!
I hope you are doing well!
I would like to get the number of following of each followers.
I tried this:
self.followers.append({
                                                "username": u["username"],
                                                #"profile_picture": u["profile_picture"],
                                                "id": u["id"].split("-")[1],
                                                "full_name": u["full_name"],
                                                "following": u["following"]
                                              })

I got an error, I checked on the ink361 page source, I didn't manage to find the solution..
I would like some tips on how you fix it! Thanks!!!

And last but not least, do you know where I can properly learn about page scraping? Thanks!

Have a good one!

**Comment by LevPasha** [comment]
Hi @taktikal17!
ink361 return JSON data like this (there is no "following"): 
```
"username":"melisa29510",
"profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/s150x150/12729657_455276428001684_1074057196_a.jpg",
"id":"ig-2792464397",
"full_name":"Melisa"
```
[example](https://data.ink361.com/v1/users/ig-15495896/followed-by)

Also you can have some error if you try to print "full_name" - it can have some emoji - console don't like it!

**Comment by taktikal17** [comment]
Hey @LevPasha!

My mad, I have no issue with your script it works like a charm.
I checked the packed.js on ink361.
I found the classes I was looking for :  `getUserFollowers` and 'getUserFollowing`. I guess there is a query to count the followers/following.

A little bit later, there were: 's.counts.followed_by' and `s.counts.follows`.

I am trying to get these information on my followers/following list:
The count of the user followers/following.

<img width="651" alt="screenshot at feb 24 22-38-09" src="https://cloud.githubusercontent.com/assets/8819239/13301982/d47e11e6-db47-11e5-9ee2-8c43a53884fe.png">


Otherwise your script is perfect. I just get the id that I write on a .txt. The idea behind this is to write on a .txt the user_id, count.followed_by, count.follows in order to make the difference between the count.follows - count.followed_by and if it is superior to a value fixed by myself, I write it on a .txt which will use in the follow function.

I didn't learn enough yet about using properly the JSON data to do the link between my thoughts and the final script.. But I am working on it!

**Comment by LevPasha** [comment]
Hi @taktikal17 if you send request on this url https://data.ink361.com/v1/users/ig-181434349 (with id you need) - you can take this info.

```json
counts: {media: 107, albums: 0, followed_by: 795723, follows: 235}
```
[Look](https://github.com/LevPasha/instabot.py/blob/master/userinfo.py#L57-L64) how i do it in `userinfo.py`  and add new function to get this info, and fork me!

**Comment by taktikal17** [comment]
I can't thank you enough @LevPasha!

I added: 

I get the follower list, get the number of follower/following of each, and I print on my .txt only if it is superior to `nb`.

I write on your list ( `followers` ) the number of follower/following.

Let me know if it is good for you!

Have a good one!
