### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PaeonGo** [LevPasha/instabot.py#300]
What is a problem ?
http://image.prntscr.com/image/ac355f309cec40a9b786db2a1ee16aaf.png

**Comment by ArtemBernatskyy** [comment]
pip install requests

**Comment by ArtemBernatskyy** [comment]
@PaeonGo  plz close asap

**Comment by PaeonGo** [comment]
Я установил

**Comment by PaeonGo** [comment]
I'm instal

**Comment by ArtemBernatskyy** [comment]
so ? any more problems

**Comment by PaeonGo** [comment]
Dont work !

**Comment by ArtemBernatskyy** [comment]
attach screenshots

**Comment by PaeonGo** [comment]
What ?

**Comment by PaeonGo** [comment]
http://image.prntscr.com/image/9bf04a99004d4121ad44eca47b23195d.png

**Comment by ArtemBernatskyy** [comment]
@PaeonGo  i don't provide that kind of support,  if you want to use python package check some of python tutorials first.

**Comment by PaeonGo** [comment]
What else could be errors in addition to Pip &

**Comment by PaeonGo** [comment]
?

**Comment by ArtemBernatskyy** [comment]
@PaeonGo  so basically you should read about python virtualenv and installing packages via pip

**Comment by PaeonGo** [comment]
Oh I'm very stupid )Sorry

**Comment by virginsince1997** [comment]
Learn basic python, in case you run into problems like this, so you can
solve them yourself

**Comment by PaeonGo** [comment]
I install all packages !But dont work !

**Comment by PaeonGo** [comment]
http://image.prntscr.com/image/8d3bea9c75094490838c351e447321f8.png

**Comment by PaeonGo** [comment]
IIIIIIIIIIIIII DOOOOOOOOOO ITTTTTTTTTTTT

**Comment by LevPasha** [comment]
@PaeonGo blocked.
