### ISSUE TITLE
i keep getting this error while trying to run example.py

### ISSUE THREAD

**Issue by virginsince1997** [LevPasha/instabot.py#303]
TypeError: __init__() got an unexpected keyword argument 'unwanted_username_list'

**Comment by smosse** [comment]
can you copy your unwanted_username_list= ?? at the begening of example.py

**Comment by virginsince1997** [comment]
@smosse unwanted_username_list=['second','stuff','art','project','love','life','food','blog','free','keren','photo','graphy','indo',
                                       'travel','art','shop','store','sex','toko','jual','online','murah','jam','kaos','case','baju','fashion',
                                        'corp','tas','butik','grosir','karpet','sosis','salon','skin','care','cloth','tech','rental',
                                        'kamera','beauty','express','kredit','collection','impor','preloved','follow','follower','gain',
                                        '.id','_id','bags'])

**Comment by smosse** [comment]
try replacing with almost empty to start
unwanted_username_list=['.id','_id'])

**Comment by virginsince1997** [comment]
Traceback (most recent call last):
  File "/home/Thefreelancedude/example.py", line 31, in <module>
    unwanted_username_list=['.id','_id'])
TypeError: __init__() got an unexpected keyword argument 'unwanted_username_list'
>>>

**Comment by smosse** [comment]
ok then copy the lines before like this, but dont show you username and password :)
`bot = InstaBot(login="username", password="password",
               like_per_day=1000,
               comments_per_day=0,
               tag_list=['follow4follow', 'f4f', 'cute'],
               tag_blacklist=['rain', 'thunderstorm'],
               user_blacklist={},
               max_like_for_one_tag=50,
               follow_per_day=5000,
               follow_time=1*60,
               unfollow_per_day=5000,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               # Use unwanted username list to block users which have username contains one of this string
               ## Doesn't have to match entirely example: mozart will be blocked because it contains *art
               ### freefollowers will be blocked because it contains free 
               unwanted_username_list=['second','stuff','art','project','love','life','food','blog','free','keren','photo','graphy','indo',
                                       'travel','art','shop','store','sex','toko','jual','online','murah','jam','kaos','case','baju','fashion',
                                        'corp','tas','butik','grosir','karpet','sosis','salon','skin','care','cloth','tech','rental',
                                        'kamera','beauty','express','kredit','collection','impor','preloved','follow','follower','gain',
                                        '.id','_id','bags'])`

**Comment by smosse** [comment]
i guess you forgot a , somewhere

**Comment by virginsince1997** [comment]
`#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys, os
sys.path.append(os.path.join(sys.path[0],'src'))

from instabot import InstaBot
from check_status import check_status
from feed_scanner import feed_scanner
from unfollow_protocol import unfollow_protocol
from follow_protocol import follow_protocol
import time


bot = InstaBot(login="username", password="password",
               like_per_day=1000,
               comments_per_day=0,
               tag_list=['follow4follow', 'f4f', 'cute'],
               tag_blacklist=['rain', 'thunderstorm'],
               user_blacklist={},
               max_like_for_one_tag=50,
               follow_per_day=300,
               follow_time=1*60,
               unfollow_per_day=300,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy='',
               # Use unwanted username list to block users which have username contains one of this string
               ## Doesn't have to match entirely example: mozart will be blocked because it contains *art
               ### freefollowers will be blocked because it contains free
               unwanted_username_list=['second','stuff','art','project','love','life','food','blog','free','keren','photo','graphy','indo',
                                       'travel','art','shop','store','sex','toko','jual','online','murah','jam','kaos','case','baju','fashion',
                                        'corp','tas','butik','grosir','karpet','sosis','salon','skin','care','cloth','tech','rental',
                                        'kamera','beauty','express','kredit','collection','impor','preloved','follow','follower','gain',
                                        '.id','_id','bags'])

`

**Comment by smosse** [comment]
if you are suing the unchange example.py file this should work.
I was thinking you missplace a ' or a , 
or missplace a 'TAB' as python is pretty unforgiven with those

**Comment by virginsince1997** [comment]
can you send me example.py without your login and password :)

**Comment by smosse** [comment]
`
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys, os
sys.path.append(os.path.join(sys.path[0],'src'))

from instabot import InstaBot
from check_status import check_status
from feed_scanner import feed_scanner
from unfollow_protocol import unfollow_protocol
from follow_protocol import follow_protocol
from text_handler import read
import time

bot = InstaBot(login="username", password="password",
               like_per_day=1000,
               comments_per_day=0,
 			   tag_list=['models', 'beauty', 'cute', 'shooting', 'photooftheday', 'love', 'beautiful', 'girls', 'picoftheday', 'instadaily', 'fashion'],
               tag_blacklist=['meat', 'gross'],
               user_blacklist={},
               max_like_for_one_tag=50,
               follow_per_day=1000,
               follow_time=1*60,
               unfollow_per_day=1000,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy='',
               # Use unwanted username list to block users which have username contains one of this string
               ## Doesn't have to match entirely example: mozart will be blocked because it contains *art
               ### freefollowers will be blocked because it contains free 
               unwanted_username_list=['.id','_id'])
               
while True:

    print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    print("## MODE 1 = MODIFIED MODE BY KEMONG")
    print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    print("#### MODE 3 = MODIFIED MODE : UNFOLLOW PEOPLE WHO DON'T FOLLOW BACK BASED ON RECENT FEED ONLY")
    print("##### MODE 4 = MODIFIED MODE : FOLLOW PEOPLE BASED ON RECENT FEED ONLY")
    print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT") 

    ################################
           ##  WARNING   ###
    ################################
    
    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD
 
    mode = 1
    
    print("You choose mode : %i" %(mode))
    print("CTRL + C to cancel this operation or wait 30 seconds to start")
    time.sleep(30)
    print("reading old following list....")
    read(bot)

    if mode == 0 : 
        bot.new_auto_mod()

    elif mode == 1 :
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10*60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) <50 :
                feed_scanner(bot)
                time.sleep(5*60)
                follow_protocol(bot)
                time.sleep(10*60)
                check_status(bot)

    elif mode == 2 :
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3 :
        while True:
            unfollow_protocol(bot)
            time.sleep(10*60)

    elif mode == 4 :
        while True:
            feed_scanner(bot)
            time.sleep(60)
            follow_protocol(bot)
            time.sleep(10*60)

    elif mode == 5 :
        while True:
            bot.bot_mode=2
            unfollow_protocol(bot)

    else :
        print ("You give me wrong mode mothafucka!!!")

`

**Comment by virginsince1997** [comment]
please readjust

**Comment by virginsince1997** [comment]
Sorry can you send an attachment, the indentations are gone

**Comment by virginsince1997** [comment]
Works like a charm
