### ISSUE TITLE
Bot Caught in Follow Loop

### ISSUE THREAD

**Issue by fusillijerry89** [LevPasha/instabot.py#305]
Keeps following same users over and over.

> Liked: 1396158493597978039. Likes: #44.
> Current Index = 0 of 9 medias
> Trying to like media: 1397592817866318566
> Liked: 1397592817866318566. Likes: #14.
> Current Index = 4 of 8 medias
> Trying to like media: 1397124429469467602
> Liked: 1397124429469467602. Likes: #22.
> Trying to unfollow: ilykihyun
> Unfollow: ilykihyun #24.
> Trying to follow: 1797636066
> Followed: 1797636066 #6.
> Trying to follow: 1797636066
> Followed: 1797636066 #7.
> Trying to follow: 1797636066
> Followed: 1797636066 #8.
> Trying to like media: 1397592817866318566
> Liked: 1397592817866318566. Like #1.
> Trying to follow: 1969793130
> Followed: 1969793130 #9.
> Trying to follow: 1969793130
> Followed: 1969793130 #10.
> Trying to follow: 1969793130
> Followed: 1969793130 #11.
> Trying to follow: 1969793130
> Followed: 1969793130 #12.
> Trying to follow: 1969793130
> Followed: 1969793130 #13.
> Trying to follow: 1969793130
> Followed: 1969793130 #14.
> Trying to follow: 1969793130
> Followed: 1969793130 #15.
> Trying to follow: 1969793130
> Followed: 1969793130 #16.
> Trying to follow: 1969793130
> Followed: 1969793130 #17.
> Trying to like media: 1397592809820726432
> Liked: 1397592809820726432. Like #2.
> Trying to follow: 2540690638
> Followed: 2540690638 #18.
> Trying to follow: 2540690638
> Followed: 2540690638 #19.

**Comment by DanielSokil** [comment]
must very much like that profile.

**Comment by gaijinjoe** [comment]
Me too.. 

Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073
Trying to follow: 1418181073

**Comment by LevPasha** [comment]
Use popular tags.
