### ISSUE TITLE
Need Help Urgent! 

### ISSUE THREAD

**Issue by 179skr** [LevPasha/instabot.py#31]
Hi, I am trying to make a follow bot which follows someone elses followers but i can't seem to make it work. If anyone has a bot which can follow someone elses followers and/or unfollow them can you please email  to me i would be really really greatful.My email is ameilakham12@gmail.com. Thank you.

**Comment by nivong** [comment]
I am sorry but this is just plain rude.
1 its not urgent
2 you can't demand someone to make anything
3 if you "need" it just pay for it and let someone make it...

**Comment by 179skr** [comment]
@nivong 

1. How would you know if its urgent or not. I think i would know not you.
2. I didn't demand. I was asking if someone could send me a script. hence the word please.
3. I didn't say i wouldnt. You simply judged to conclusions.

**Comment by nivong** [comment]
Need Help Urgent! #31
Read your title.
you just need it for your own app.... who says you are not going to make money out of it? it's just a really wrong way of asking all of this and very rude in my opinion

**Comment by 179skr** [comment]
@nivong 
I'm sorry
Its for a class project i'm doing. Not a money making scheme. The reason i put urgent was because of the deadline date. 

Sorry again.

**Comment by LevPasha** [comment]
@nivong you like my personal lawyer ))
@179skr sorry i have now time to make individual app for everyone who asks. A like to help with some questions about `InstaBot`, if you need class project - make it youself - this is useful.

**Comment by Moderndayfreak** [comment]
Ouch! 
Respectfully speaking... A nominal fee would help a coder out 👍😝
