### ISSUE TITLE
like_per_day formula not functioning / Bot liking too quickly

### ISSUE THREAD

**Issue by questionhere** [LevPasha/instabot.py#314]
No matter what value the like_per_day is set at (1000 or 500) and the time I change the bot to run in (0 to 23 hours, or 13 to 14 hours), the like rate does not change.

I know the formula says that it is 24 * 60 * 60 / likevalue but it does not seem to change when I change example.py's like_per_day value

**Comment by thomas10154** [comment]
got the same issue. Think the sleep function isn't working properly. don't have the knowledge to fix it myself though :(

**Comment by slimline33** [comment]
same to me. I downgraded to an older commit...

**Comment by manoufeb** [comment]
@slimline33 which commit did you take? :)
Thanks!

**Comment by gaijinjoe** [comment]
Me too

**Comment by Hammanek** [comment]
So you all are getting blocked, right? Bcause I do.. I tried 950 likes par day, then 500 likes.. no change.. blocked again.

**Comment by LevPasha** [comment]
@nivong ?

**Comment by nivong** [comment]
https://github.com/LevPasha/instabot.py/issues/313#issuecomment-267938864
same issue, please close other one, will have a look found the same issue. But it's not liking to fast its something else

**Comment by froggyfreshrap** [comment]
My instagram got blocked for liking too fast, what settings should u use when liking to not get blocked?

**Comment by questionhere** [comment]
download an older version. i downloaded a version from august and it worked
fine.
