### ISSUE TITLE
Bot running time issue

### ISSUE THREAD

**Issue by skuseme** [LevPasha/instabot.py#323]
Traceback (most recent call last):
  File "./bot.py", line 35, in <module>
    bot_running_hour_end = 20
TypeError: __init__() got an unexpected keyword argument 'bot_running_hour_end'

Looks like the function/class was taken out of src/instabot.py in commit _0039779a5ae30f0247def42479da32b2719f0820_ however the configuration for it was not taken out of the example.py

**Comment by fajriwip** [comment]
have same problem, for now i'm not using the running time

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/commit/acdaaa958db775155e7dbbcf3231a62d62048231
