### ISSUE TITLE
__init__() got an unexpected keyword argument 'bot_running_hour_start'

### ISSUE THREAD

**Issue by da-muck** [LevPasha/instabot.py#326]
[example.zip](https://github.com/LevPasha/instabot.py/files/671750/example.zip)

I downloaded the Bot and just changed username, password and number of likes per day, but I get this error:

pi@raspberrypi:~/instabot $ python3 example.py
Traceback (most recent call last):
  File "example.py", line 39, in <module>
    bot_running_hour_end = 23)
TypeError: __init__() got an unexpected keyword argument 'bot_running_hour_start'

I also deleted the comment for start and end houre because I thought the error would be there.
Any Ideas?

**Comment by lgs777** [comment]
I have same issue :(

**Comment by polaroi8d** [comment]
IMHO in the last commit there is a wrong code. Try it with 49c2ac9c1c08f38a6c598ac4bcdab60f0cd0562d this hash.

**Comment by da-muck** [comment]
Can you please upload a correct working file so we can download it?

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/commit/acdaaa958db775155e7dbbcf3231a62d62048231
