### ISSUE TITLE
Instagram blocked

### ISSUE THREAD

**Issue by aliarifsoydas** [LevPasha/instabot.py#330]
I was using that bot on my computer for a while, yesterday I just moved everything on my server and started to run script. (I have 2 different accounts) For an account is working perfect but for second one I can not login. When I try I get blocked from Instagram. 

Should I set proxy for bypass it?

**Comment by LevPasha** [comment]
Maybe you have 2f autorixation there? I run 4-5 account from 1 ip.

**Comment by aliarifsoydas** [comment]
I was using 4 different accounts from my computer, now I moved to my server and I can not use 2 of them together.  When I try to connect, directly gives me an error. I don't know what should I do.

and at same same I can connect that account from my computer.

**Comment by LevPasha** [comment]
Look like IG don't like your server ip.

**Comment by aliarifsoydas** [comment]
After a while I run script again and now it works very well.

Thanks :+1: :)
