### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by mkrutiy** [LevPasha/instabot.py#335]
I keep getting the following error when trying to run example.py (with my changed settings, including username and password):

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
  File "/.../instabot.py/src/instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "/.../instabot.py/src/userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests

Any ideas as to how to fix this?

**Comment by fueg0** [comment]
Try: $ pip install requests

**Comment by aliguy** [comment]
Had that problem, I had previously installed 3 but had uninstalled it afterwards to run a program with deprecated functions - try running it on different versions of IDLE

**Comment by tbudd23** [comment]
C:\>python -m pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 366kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.1

C:\>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
ImportError: No module named 'instabot'

**Comment by tbudd23** [comment]
any idea as to why this isn't working?  I installed the new files.  "No mudule names 'instabot'?

**Comment by gersanchez** [comment]
just move example.py into src folder! that work for me!

but my error was a little different.
.
<img width="633" alt="captura de pantalla 2017-02-20 a las 6 08 32 p m" src="https://cloud.githubusercontent.com/assets/2736208/23149890/30599778-f7bd-11e6-820e-3721c179ea9f.png">

**Comment by fixduino** [comment]
*SOLVED* for me with move file example.py to folder src. thanks

**Comment by Lukavalls** [comment]
where is the src. folders? thanks!
