### ISSUE TITLE
Keeps trying to follow the same user

### ISSUE THREAD

**Issue by froggyfreshrap** [LevPasha/instabot.py#343]
It keeps followering the same user, instead of following new users. 
What am I doing wrong?

Followed: 197142668 #1.
Trying to follow: 197142668
Followed: 197142668 #2.
Trying to follow: 197142668
Followed: 197142668 #3.
Trying to follow: 197142668
Followed: 197142668 #4.
Trying to follow: 197142668
Followed: 197142668 #5.

**Comment by virginsince1997** [comment]
Try using a popular Tag maybe

**Comment by froggyfreshrap** [comment]
@virginsince1997 
I changed the tags to more popular ones and it still keeps following the same user.
Trying to follow: 1971017106
Followed: 1971017106 #1.
Trying to follow: 1971017106
Followed: 1971017106 #2.
Trying to follow: 1971017106
Followed: 1971017106 #3.
Trying to follow: 1971017106
Followed: 1971017106 #4.
Trying to follow: 1971017106
Followed: 1971017106 #5.
Trying to follow: 1971017106
Followed: 1971017106 #6.

**Comment by angelskieglazki** [comment]
I have same problem:)

**Comment by LevPasha** [comment]
Try default tags and set like per day > follow per day.

**Comment by froggyfreshrap** [comment]
@LevPasha 
Thanks, its working now!
