### ISSUE TITLE
New Comments

### ISSUE THREAD

**Issue by aparcedo** [LevPasha/instabot.py#344]
Hi,

I'm trying to change the comments list and i do not find them.

i want to add my own comments

**Comment by juanmiconlup** [comment]
src>instabot.py> lines 592-603

![image](https://cloud.githubusercontent.com/assets/19253629/21741929/26b07742-d4e4-11e6-9233-14e091fe33f9.png)

**Comment by aparcedo** [comment]
Thanks. I did it. i add them in spanish...
