### ISSUE TITLE
error bot.follow

### ISSUE THREAD

**Issue by i-diot** [LevPasha/instabot.py#347]
If you specify id username ,
bot.follow('id1', 'id2', 'id3',)

gives an error message

Traceback (most recent call last):
  File "example.py", line 37, in <module>
    bot.follow('1784434763', '419284352', '227747340',)
TypeError: follow() takes exactly 2 arguments (4 given)
Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:08.799784
Logout success!
Exception KeyError: KeyError(140380015231872,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by LevPasha** [comment]
@i-diot follow function don't take list. Use follow in loop.

**Comment by Abzidian** [comment]
Could you please help?
bot.unfollow('12344') says syntax error
