### ISSUE TITLE
New issue here

### ISSUE THREAD

**Issue by duedares11** [LevPasha/instabot.py#349]
I get these errors once i run the bot.
![screenshot_30](https://cloud.githubusercontent.com/assets/15311322/21841620/e4947706-d7da-11e6-8c62-5b2038b3c669.png)

**Comment by gilllambrigts** [comment]
Hi there duedares11.

Could you copy your source code of the file example.py onto this thread? 

Gill

**Comment by duedares11** [comment]
There were some minor issues.
Just fixed.
Thanks anyway. :)
