### ISSUE TITLE
follow to followers of the profile

### ISSUE THREAD

**Issue by mugukamil** [LevPasha/instabot.py#36]
привет можно ли выбрать определенный профиль в инсте и чтобы скрипт подписывался на всех его подписчиков, лайкал их и комментировал? точно так же как сейчас это просиходит с тегами?

**Comment by LevPasha** [comment]
Привет, это не реализовано "из коробки", но возможно с помощью `userinfo.py`. Форкай потом что получилось.

**Comment by amk11** [comment]
@LevPasha how would you use userinfo.py? i've tried to do that but it doesnt seem to follow anyone.

**Comment by LevPasha** [comment]
@amk11 `userinfo.py` just aggregate some user info, and than you should do somethink with this.
