### ISSUE TITLE
follow_per_day not working

### ISSUE THREAD

**Issue by yonimm** [LevPasha/instabot.py#360]
i tried few times to follow users and is only make likes
this is my code:
               like_per_day=1000,
               comments_per_day=0,
               tag_list=["like4like", 'f4f', 'followme','follow4follow'],
               tag_blacklist=['rain', 'thunderstorm'],
               user_blacklist={},
               max_like_for_one_tag=15,
               follow_per_day=400,
               follow_time=1 * 60,
               media_max_like=15,
               unfollow_per_day=400,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy='',
  unwanted_username_list=['second',......
bot.auto_mod()

**Comment by loganyc1934** [comment]
`unfollow_per_day` also seems not working

**Comment by yonimm** [comment]
@loganyc1934 to fix that you need to update your project.
work for me.
