### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by TheIndra55** [LevPasha/instabot.py#369]
Is there any method for posting a story?

**Comment by TheIndra55** [comment]
Never mind found it at another api 😄

**Comment by gersanchez** [comment]
@TheIndra55 what api!!??¿?¿?

**Comment by ahangarha** [comment]
I am looking for this functionality. I didn't understand what you (@TheIndra55) meant by saying 

> Never mind found it at another api smile

May you clarify please?

**Comment by TheIndra55** [comment]
@ahangarha I'm now using https://github.com/mgp25/Instagram-API
