### ISSUE TITLE
"Mode 5" does not continue after 24th unfollow 

### ISSUE THREAD

**Issue by egurdal-reidin** [LevPasha/instabot.py#370]
When I use mode = 5, function starts as usual but stucks at 24th unfollow and never continue. I have to restart every 24 unfollow. Did I forget to change somewhere in configuration?

**Comment by Gabrieldenys** [comment]
I'm having the same problem, can't figure out what it is.  From my research there is a limit in unfollow_protocol.py 

limit = random.randint(10,22) +1

Try changing that to limit = 999999 or whatever number you please and see if that works for you.

**Comment by egurdal-reidin** [comment]
Thanks for your feedback @Gabrieldenys  I tried and it works well.

**Comment by rhetthamm** [comment]
I tried going into the file unfollow_protocol.py and changing the limit to limit = 999 and many other options but it still only shows media in recent feed=24 and stops unfolding after 24. Please help. What is going wrong?
