### ISSUE TITLE
Bot randomly stops working on Raspberry Pi

### ISSUE THREAD

**Issue by marfert** [LevPasha/instabot.py#387]
I am running the bot in **mode 0** on a Raspberry Pi and start it with the following command:

`nohup python example.py &`

After a seemingly random time it quits as if I would have make it stop, but I didn't.

Examples of the log:

2017-02-13 01:01:50,538 - x - Logout: likes - 3193, follow - 865, unfollow - 454, comments - 575.
2017-02-13 01:01:50,539 - x - Bot work time: 3 days, 4:13:37.587617
2017-02-13 01:01:50,882 - x - Logout success!

2017-02-20 00:50:07,451 - x - Logout: likes - 108, follow - 17, unfollow - 9, comments - 41.
2017-02-20 00:50:07,452 - x - Bot work time: 2:04:13.018695
2017-02-20 00:50:07,759 - x - Logout success!

I want the bot to run 24/7. Does anybody have an idea what could be wrong?

Here is my configuration:

```
bot = InstaBot(login="user", password="pass",
               like_per_day=1440,
               comments_per_day=300,
               tag_list=['tag1', 'tag2'],
               tag_blacklist=['rain', 'thunderstorm'],
               user_blacklist={},
               max_like_for_one_tag=20,
               follow_per_day=50,
               follow_time=7*24*60,
               unfollow_per_day=0,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy='',
               media_max_like=25,
               media_min_like=5,
               # Use unwanted username list to block users which have username contains one of this string
               ## Doesn't have to match entirely example: mozart will be blocked because it contains *art
               ### freefollowers will be blocked because it contains free
               unwanted_username_list=['second','stuff','art','project','love','life','food','blog','free','keren','photo','graphy','indo',
                                       'travel','art','shop','store','sex','toko','jual','online','murah','jam','kaos','case','baju','fashion',
                                        'corp','tas','butik','grosir','karpet','sosis','salon','skin','care','cloth','tech','rental',
                                        'kamera','beauty','express','kredit','collection','impor','preloved','follow','follower','gain',
                                        '.id','_id','bags'])
```

**Comment by slimline33** [comment]
I have the same issue. I restart the bot and thats okey for me.

**Comment by marfert** [comment]
For me it is not okay because I do not monitor the Raspberry Pis activity all the time. I now created a script that checks, if the bot process is running and run the script every minute as a cronjob. That works fine for me.

**Comment by slimline33** [comment]
Would you make your script public?

**Comment by marfert** [comment]
Sure, just replace example.py two times by the name of your file. The script must be in the bots root folder.

```
#!/bin/bash
if ps aux | grep [e]xample >/dev/null ;then
   echo "up"
else
   echo "down"
   nohup python example.py &
fi
```

**Comment by slimline33** [comment]
thanks a lot!

**Comment by limerick11** [comment]
@marfert I have the same issue, but I don't understand your post. What do I name the file? Is it a job that I need to add to the crontab?
