### ISSUE TITLE
How to use Userinfo()

### ISSUE THREAD

**Issue by amk11** [LevPasha/instabot.py#39]
Hi, How would you use userinfo() to follow someone elses followers?
Ive tried getting the Ids and putting them into bot.follow() but that doesnt work.

**Comment by LevPasha** [comment]
I think it must work, show your code.

**Comment by amk11** [comment]
ui = UserInfo()
bot = InstaBot('username', 'password',
                         log_mod = 0)

ui.search_user(user_id="50417061")
ui.get_followers(limit=5)
bot.follow(["id"])
bot.logout()

**Comment by LevPasha** [comment]
`ui.get_followers(limit=5)` return list. Try something like this:
```python
for f in ui.get_followers(limit=5):
    bot.follow(f)
    time.sleep(60) # if you need
bot.logout()
```

**Comment by amk11** [comment]
for f in ui.get_followers(limit=5):
    bot.follow(f["id"])
    time.sleep(60) # if you need
bot.logout()

Doesn't seem to work. I get this error.

Traceback (most recent call last):
  File "/home/amk/instabot-master/example.py", line 10, in <module>
    for f in ui.get_followers(limit=5):
TypeError: 'bool' object is not iterable

**Comment by amk11** [comment]
Sorry i  closed this issue on accident.

**Comment by LevPasha** [comment]
@amk11 sorry, my mistake:

```python
ui.get_followers(limit=5)
for f in ui.followers:
    bot.follow(f["id"])
    time.sleep(60) # if you need
bot.logout()
```

**Comment by amk11** [comment]
Thanks that worked!, Can following also have a limit? For example 

ui.get_following(limit=10)

Ive tried that code but doesn't seem to work.

**Comment by LevPasha** [comment]
@amk11  `ui.get_following(limit=10)` should work!
