### ISSUE TITLE
Works great on Windows but not on Linux

### ISSUE THREAD

**Issue by CHollasch** [LevPasha/instabot.py#392]
I have a Linux VPS that I'm trying to run this on. I can connect to Instagram just fine via Firefox so it doesn't look like an IP block, but when using the bot it gives a connection error (code 400). I can also run the same exact python script on my Windows machine just fine. Any idea?

**Comment by LevPasha** [comment]
You need to login to IG APP and press "IT WAS ME"

**Comment by CHollasch** [comment]
I've done that multiple times already. Already resolved this issue as the machine I was using was probably blacklisted by Instagram.
