### ISSUE TITLE
Bot trying to unfollow user id 12345

### ISSUE THREAD

**Issue by dadealer** [LevPasha/instabot.py#396]
Since hours the bot try to unfollow the user with the id 12345. this number is based in instabot.py as basic variable.

Any option to solve this bug?

**Comment by dadealer** [comment]
@levpasha this is not bug. This happens because the unfollow routine got the error from the get media routine

**Comment by alexislevrai** [comment]
Same problem here, have you find a solution for this ?

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/pull/402

**Comment by MrTwIXx** [comment]
@LevPasha @alexislevrai 

This problem is up again now. It always wants to get the media from a ex acc
