### ISSUE TITLE
except on get_media 

### ISSUE THREAD

**Issue by virginsince1997** [LevPasha/instabot.py#397]
for some reason recently i been unable to like pictures on my feed
please anyone knows what could be wrong? or if you have a feedliker script to share ,,

Trying to unfollow #%i:
luxurybeyondyou : Get media id on recent feed
Except on get_media!

**Comment by dadealer** [comment]
Because instagram change some parts of the api

**Comment by kemong** [comment]
the bot needs to be rewritten XD

**Comment by virginsince1997** [comment]
@kemong lol where have you been
