### ISSUE TITLE
unexpected indent

### ISSUE THREAD

**Issue by cahyonegoro** [LevPasha/instabot.py#4]
mine have an error after i paste this :
		bot = InstaBot('login', 'password',
               like_in_day=1000,
               more_than_likes=10,
               tag_list = ['cat', 'car', 'dog'],
               max_like_for_one_tag=5,
               log_mod = 0)

at the end of the line

the error says : IndentationError: unexpected indent and the cursor is in bot

**Comment by LevPasha** [comment]
@cahyonegoro hi! I think you need google your error before creating issue: [indent-in-python](http://stackoverflow.com/questions/1016814/what-to-do-with-unexpected-indent-in-python)
