### ISSUE TITLE
no module "request" in sc

### ISSUE THREAD

**Issue by LeonardSylvester** [LevPasha/instabot.py#400]
when I try to execute: 'python example.py'

this ImportError appears

GitHub/instabot.py/src/userinfo.py", line 4, in <module>
    import requests
**ImportError: No module named requests**

how can I fix this?

**Comment by lotusrs** [comment]
@LeonardSylvester 
try `pip install requests`

**Comment by LeonardSylvester** [comment]
perfect, this solved the problem. thank u!

**Comment by ekremgurdal** [comment]
before trying to open a new issue please look up closed issues first. Your issue fixed million times.
