### ISSUE TITLE
"already in ex user list" Error

### ISSUE THREAD

**Issue by ProgrammingDude** [LevPasha/instabot.py#401]
Hi, 
the Instagram API got changed it think and since then all bots are not working anymore(makes totally sense, because Lev didnt't update the bot).

Does anyone already fix it?

Please Lev, I appreciate your work. Please fix the  bot🙏🏽

Would be nice to get some help!

-Jason

**Comment by Redhead9** [comment]
Same here, likes and comments still work though.

**Comment by gferrer807** [comment]
Same, the like and follow feature still works for me, but not the unfollow features

**Comment by MrEmuu** [comment]
Same here, just sticks un ex user and unfollowing no longer works.

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/pull/402
