### ISSUE TITLE
Unfollow not working at all

### ISSUE THREAD

**Issue by gferrer807** [LevPasha/instabot.py#405]
list of all the things I've tried

-(1) Set bot mode to 5, and tried all other modes

-(2) change line 680 on instabot.py from `if follower/follows > 2` to `if follower > 2`. If an account was labeled as a selebgram account, it would not be deleted.

-(3) changed the limit on line 13 in unfollowporotocol.py from `limit = random.randint(10,22)+1` to `limit = random.randint(10,999999)+1`

For a time the unfollow feature worked, granted it would stop after the 24th unfollow.  Change 3 fixed that problem for some but not for me. I accidentally deleted the file that successfully unfollowed up to 24 people and now I cant get it to work again.

I'm going to try downloading the bot again and making these changes. Maybe I made some changes I don't remember? But currently, from what I can tell, those are the only changes I made and no luck so far. Let's please try to get this unfollow feature working again. Thanks!

**Comment by drhtcl** [comment]
Same is happening to me

**Comment by gferrer807** [comment]
@drhtcl please make any or all of the changes i listed in my comment, and let us know if anything changed for you. 

If no one has a solution they can offer, I would ask to please make the changes and report back with the new results if there are any. This way we can isolate what works and/or what needs fixing. Thanks!

**Comment by drhtcl** [comment]
Just tried that, still doesnt work. He keeps trying to unfollow the same user over and over.
Others believe that is due to the change in instagram API: https://github.com/LevPasha/instabot.py/issues/401

**Comment by gferrer807** [comment]
@drhtcl ahh I see. Well I'm going to leave this open anyways. Hopefully we can find a solution at some point.

**Comment by fearthedear** [comment]
I added a PR with fix for this, see [here](https://github.com/LevPasha/instabot.py/pull/402)

**Comment by gferrer807** [comment]
@fearthedear going to try it in an hour. Thanks for the heads up!

**Comment by gferrer807** [comment]
@fearthedear I tried the fixes. I'm still only getting a userinfo list. The unfollow feature still isn't working. This is all im getting [http://imgur.com/a/nWJuE](url)

**Comment by fearthedear** [comment]
Seems to be a partial fix then, for me it works in mode 0 on macOS and linux.

http://imgur.com/3bZur6P

**Comment by alexislevrai** [comment]
I just try your fix ans it's a good start.
It's partially fixed, because the bot randomly unfollow an account, but not the account that he follow X  seconds (follow_time) before.

I tested this in Terminal macOS

**Comment by gferrer807** [comment]
The following fix still isn't working for windows. If any other windows users can leave feedback on what works/doesn't it would be appreciated! :)

**Comment by chanjohnathan** [comment]
Working for me on Windows with mode 0. Side note, but is mode 2 supposed to work? Even with this fix it doesn't seem to work.

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/pull/402
