### ISSUE TITLE
Bot only try unfollow "abcd" account all the time

### ISSUE THREAD

**Issue by alvarongg** [LevPasha/instabot.py#408]
I did not do any special configuration, I tried several things without solution. To that account I am not following, but the bot is the only account that tries to stop following again and again.

Does anyone have a similar problem?

**Comment by alexislevrai** [comment]
Similar problem [here](https://github.com/LevPasha/instabot.py/issues/405) and [here](https://github.com/LevPasha/instabot.py/issues/396)

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/pull/402
