### ISSUE TITLE
Кое-что добавил.

### ISSUE THREAD

**Issue by ictek05** [LevPasha/instabot.py#42]
Хз как тут код свой предлагать. 

Добавил поддержку русских тэгов, заменил облако комментариев на русские комменты. Также добавил счетчик времени работы скрипта. Иногда не хватало инфы о том сколько уже работает бот от момента его запуска. Теперь в консоле отображается время с момента запуска бота после того как он кого-то лайкает.
 
[instabot.txt](https://github.com/LevPasha/instabot.py/files/207938/instabot.txt)

**Comment by LevPasha** [comment]
Не успел пока посмотреть. Свое предлагать - сделай pull request - мне так удобнее будет. Спасибо.

**Comment by FincherFincher** [comment]
Подскажите, что-то не получается с русскими тэгами запустить "'utf-8' codec can't decode byte". Побывал через tag= unicode(tag, 'cp1251'), что-то не выходит. Заранее спс Вам!

**Comment by LevPasha** [comment]
@FincherFincher а какая версия питона?

**Comment by FincherFincher** [comment]
@LevPasha 3.5

**Comment by ictek05** [comment]
@FincherFincher А должен быть - 3

**Comment by LevPasha** [comment]
@FincherFincher @ictek05 у меня на сервере 3.4.2, нет времени проверять под каждой из версий.

**Comment by samosad** [comment]
PR с изменениями из файла .txt 
https://github.com/LevPasha/instabot.py/pull/64
