### ISSUE TITLE
Login Error!

### ISSUE THREAD

**Issue by amk11** [LevPasha/instabot.py#43]
Hi, I keep getting the following error "Login Error! Check your login data" My password is correct and i can still access the instagram from my web browser. I dont know how to fix this problem. P.S my bot logs in and out every 10 mins.

**Comment by LevPasha** [comment]
Show your code...

**Comment by jasux** [comment]
hey sorry for the dumb question. But i added to instabot.py with my own settings. but it wont execute. Can you please upload your version with your settings so i only have to change the login and see if that works?

**Comment by LevPasha** [comment]
@jasux download all, and use `example.py` with your login and pwd.

**Comment by amk11** [comment]
Fixed it. Instagram temporary blocked me for liking too much.
