### ISSUE TITLE
Run 2 accounts 

### ISSUE THREAD

**Issue by Sacheenlittlefeather** [LevPasha/instabot.py#435]
Hi,

How can I run 2 instagram accounts at the same time? I use IDLE.

**Comment by ChipWolf** [comment]
Run two bots?

**Comment by p53ud0k0d3** [comment]
You can run multiple instances of IDLE/Python shell at the same time. So open IDLE and run the code, and then open up IDLE again, which will start a separate instance and then run your next code.

**Comment by Sacheenlittlefeather** [comment]
Thanks guys, I tried that but it is not working. I can open separate codes in IDLE but not run them at the same time. When I run the second code I see in shell that the first code stops and the second account is logged in. How come both codes run in the same shell? Is that normal..

**Comment by ChipWolf** [comment]
Open a second copy of IDLE, don't run the same code twice in the same Window, that won't work.

**Comment by Sacheenlittlefeather** [comment]
Thanks!! I figured it out.

 I work on mac so I had to open a second window in my terminal. But Its working now!!

**Comment by kcalifdimy** [comment]
please  am a newbie am using kali linux i want run multiple instagram account with instabotpy in need a some detailed information on how to this Thanks

**Comment by Bigemm** [comment]
@kcalifdimy I'm a newbie as well but at least try before asking. There's a README file in this repo, pretty simple to follow. Additionally, for things you don't understand you can youtube them. That's what I do anyway, i only come here if everything i've already tried doesnt work; they're making the code for us to use least we can do is try first lol

**Comment by ChipWolf** [comment]
@kcalifdimy not sure why you're using Kali, there's some serious legal implications if you start messing about with some of those tools in the wrong place.
To answer your question, just run multiple bots

**Comment by kcalifdimy** [comment]
lol thanks all

**Comment by laibamughal** [comment]
i have installed python but still my instabot dont run properly black window appears for 1 or 2 second and dan disappears i dont understand what to do with it can u guide me how to make it run properly ?

**Comment by virginsince1997** [comment]
Run it in IDLE so you can see the error
