### ISSUE TITLE
Any suggestions on the # of Cron Jobs per day?

### ISSUE THREAD

**Issue by Moderndayfreak** [LevPasha/instabot.py#46]
@LevPasha How many times are you running a cron job on your server? Thanks!

**Comment by LevPasha** [comment]
@Moderndayfreak i have no cron, i start bot, and it work about week, then i restart it (too big log file). And it work for 2-5 parallel instagram accounts for 1000 likes each.

**Comment by Moderndayfreak** [comment]
Wouldn't it be better just to create a cron job and have this automated at least once a day?

**Comment by LevPasha** [comment]
@Moderndayfreak you can do like you want!
