### ISSUE TITLE
Only unfollow

### ISSUE THREAD

**Issue by zhukandrey** [LevPasha/instabot.py#47]
Привет!
Может ли бот работать просто в режиме отписки?

Когда выставляю лайки, подписки и коменты в 0, а отписку в любое число - бот ничего не делает.

**Comment by LevPasha** [comment]
@zhukandrey сейчас бот умеет отписываться только от того, кого сам зафоловил. Можно так: получить список тех кого нужно отфолловить из `userinfo.py` и потом прогнать в цикле через функцию `bot.unfollow()`

**Comment by zhukandrey** [comment]
@LevPasha  Спасибо за ответ!
