### ISSUE TITLE
bot.auto_mod()  NameError: name 'bot' is not defined

### ISSUE THREAD

**Issue by jaguar754** [LevPasha/instabot.py#5]
Im getting this error when im runing instabot.py   
```

bot.auto_mod()
NameError: name 'bot' is not defined
```

**Comment by LevPasha** [comment]
@jaguar754 OMG! You kidding me? If you don't know nothing about programming, i can't teach you! This is issue about `instabot.py`, not about "teach my, i'am don't know nothing"!

TRY TO READ README!

Standard use (will like by loop, all default tag):
`bot = InstaBot('login', 'password')`
`bot.auto_mod()`
