### ISSUE TITLE
Start multiple session?

### ISSUE THREAD

**Issue by DarkSearinox92** [LevPasha/instabot.py#50]
Hi, how can i start two times the bot? For example if i open twice cmd and start two different bot, the first start to work, and the second become the "principal". There is a way to start more times the python program?

**Comment by LevPasha** [comment]
@DarkSearinox92 hi, there is now problem with this. I have 5 parallel bot.

**Comment by DarkSearinox92** [comment]
And what is the solution?
Il 14 apr 2016 10:44 PM, Pasha Lev <notifications@github.com> ha scritto:@DarkSearinox92 hi, there is now problem with this. I have 5 parallel bot.
