### ISSUE TITLE
Start Multiple session 2 (need reply...)

### ISSUE THREAD

**Issue by DarkSearinox92** [LevPasha/instabot.py#51]
Hi, why have you closed the issues? i don't understand your reply, sorry... "hi, there is now problem with this. I have 5 parallel bot." Ok, but what are you mean with "there is problem with this?" How can i resolve this problem? Can you explain me? how can you have 5 session if "there is problem now"?

**Comment by LevPasha** [comment]
I execute `instabot.py` 5 times, with different settings. 
I close issue, because this is question about python, not about `instabot`.

**Comment by polaroi8d** [comment]
@DarkSearinox92 try [stackoverflow](https://stackoverflow.com/questions/tagged/python)

**Comment by DarkSearinox92** [comment]
Hi pasha and polaroid. Sorry for late but in this days i'haven't time to reply. Ok, let's clear something. I rewrite my error. Maybe, you've understand wrong, or, i understand wrong... I've execute the bot, writing on cmd python (and here the path) and the script start. It connects to the account and work perfectly. Then, i start another cmd, write pyton and add the path to another script that connects another account and i put the two smartphone in front of me. The results: the two script continue working without errors... Try to like. Like. Try to comment, commebt. Etc... BUT. The First account don't recive anything and new notify don't popup. AND the second account start to show popup. So.... Where is the error? What can i do?

**Comment by DarkSearinox92** [comment]
I miss that when i start the First script, the First account recive notify of course, but in the time that i start the second, the First account stop recive popup, but the script continue working...

**Comment by LevPasha** [comment]
@DarkSearinox92 hmm... I don't have any idea about your problem. I have server on Linux, and there work 4-5 bot in same time, started like you start. When i test bot on Windows - i run from CMD 2-3 bot in same time and don't have any problem. Do you make some code changes? Show me files you start.

**Comment by polaroi8d** [comment]
Tested on Raspian OS and Ubuntu 15.10, and work fine.

**Comment by DarkSearinox92** [comment]
Hi guys, i don't understand why now, it apparently work with two session... i really don't know why in the first try, the second disable the first :/ Sorry for all guys... It works perfectly with two istances now. Thank you very much for all help.

**Comment by polaroi8d** [comment]
Good to here it :) maybe they are blocked each others...

**Comment by DarkSearinox92** [comment]
Hi pasha. I've a question... Are you able to make a bot for the site worldcosplay.net?
Il 19 apr 2016 8:56 PM, Pasha Lev <notifications@github.com> ha scritto:Closed #51.

**Comment by LevPasha** [comment]
@DarkSearinox92 hi, write me on skype and we talk about it: lev_pasha

**Comment by techinpark** [comment]
how many account can running at the same time ?

**Comment by polaroi8d** [comment]
@techinpark i think there is no upper bound, im actually running 3 at the same time.
