### ISSUE TITLE
Cant work it out

### ISSUE THREAD

**Issue by safeasfcuk** [LevPasha/instabot.py#54]
Iv copied the example file with my login details into instabot and get the following error 
File "instabot.py", line 502
SyntaxError: Non-ASCII character '\xe2' in file instabot.py on line 502, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Im running this on a mac in terminal have installed latest pips

**Comment by polaroi8d** [comment]
You've got a stray byte floating around. You can find it by running
```
with open("x.py") as fp:
    for i, line in enumerate(fp):
        if "\xe2" in line:
            print i, repr(line)
```
where you should replace "x.py" by the name of your program. You'll see the line number and the offending line(s).

from here: [stackoverflow](http://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file)

**Comment by safeasfcuk** [comment]
turned out to be " instad of ' thanks

**Comment by LevPasha** [comment]
@safeasfcuk check file encoding. https://www.python.org/dev/peps/pep-0008/#source-file-encoding
