### ISSUE TITLE
Not liked: 400

### ISSUE THREAD

**Issue by alexlaza10** [LevPasha/instabot.py#58]
Hey** Levpasha **i want you to thank you for your last work the instabot is amazing.

But i have some Issues like this : 

Insta Bot v1.0 start at 25.04.2016 20:57:
Try to login by abcdefg...
Look like login by abcdefg success!
Get media id by tag: amazing
Try to like media: 1236402241810203660
Not liked: 400
Try to follow: 431624083
Try to comment: 1236402238339928209
Try to like media: 1236402238339928209
Not liked: 400
Try to like media: 1236402234924759814
Not liked: 400
Get media id by tag: rio
Try to like media: 1236402582012339580
Not liked: 400

First it worked 2 days, but then i get the [**Not liked: 400**] Issue.

**Comment by LevPasha** [comment]
@alexlaza10 hi! It look like ` #If instagram ban you - query return 400 error.` Stop like, wait about one day, and run bot again.
I think you like more than 1000 likes at day...

**Comment by alexlaza10** [comment]
ok levpasha thank you for your response .

**Comment by alexlaza10** [comment]
Hey levpasha, is it possible to implement the Python script on a Website. It should be like the instagress-Website, i dont think it would work, because i think it requires the access token and api to authenticate on a Website like this one. 

Thank you for your advise.

**Comment by hanoncs** [comment]
FYI: I had this issue just now on a brand new account. Turned out that the link in my profile was not allowed. After removing it, I was able to like right away from the bot.

**Comment by rulhaller** [comment]
what do you mean "the link in your profile??'' i have the same error

**Comment by absint0o** [comment]
i'm having the same error too...

**Comment by tonylook** [comment]
Same error too... I waited 2 days and it's still present.

**Comment by austkel** [comment]
Same issue. Long since been working but just recently happened. I suspect Instagram is updating their bot detection algorithms.

**Comment by Gymrat** [comment]
same issue, any idea the resolution?

**Comment by andpoi** [comment]
Also having the same issue...

**Comment by vinceze** [comment]
same issue for me too

**Comment by ethanwp28** [comment]
Also having this issue. Can like pictures on the regular app but not using the bot. Maybe we will have a fix for this issue soon?

**Comment by hanoncs** [comment]
Its an Instagram bot, what do you think I mean by "Link in my profile"?

**Comment by vinceze** [comment]
@hanoncs the link in your bio can affect your Instagram limits.

**Comment by meatpocketz** [comment]
Im having the same issue. Ive removed the link in my bio but have the same result. Any ideas?

**Comment by FlavianoMucedda** [comment]
Why can't we have a clear answer instead of speculation? does anyone fixed this?
