### ISSUE TITLE
unfollow personal friends

### ISSUE THREAD

**Issue by saymyname89** [LevPasha/instabot.py#60]
I have a pletora of friends that i don't want to unfollow; just wondering if the unfollow feat would unfollow - literally - all my friends, included my old one that I added without the bot.

**Comment by LevPasha** [comment]
This functionality is not present.

**Comment by saymyname89** [comment]
Thanks for reply,
and it's possible to unfollow everybody but a list of account id?

**Comment by LevPasha** [comment]
There is no ready solution, but you can write it yourself.

**Comment by saymyname89** [comment]
thx
