### ISSUE TITLE
How to Set Unfollow Delay

### ISSUE THREAD

**Issue by hockycoky** [LevPasha/instabot.py#62]
I tried to unfollow 10 following by id, but it seems there is no delay in the unfollow process.
My Code : 

bot = InstaBot('my_username', 'my_pass')
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.unfollow(xxxxxxxxxx)
bot.logout()

Is i write a wrong code??
How can i fix it??

**Comment by ageorgios** [comment]
you can use something like this:
```
import time
import random
    time.sleep(15 + 10 * random.random())
```

**Comment by hockycoky** [comment]
Yeaa, it's work... Thanks @ageorgios ..
