### ISSUE TITLE
Unfollow function

### ISSUE THREAD

**Issue by Kaziusg** [LevPasha/instabot.py#63]
Hi, I would like the bot to unfollow the users from my followed users list, I was wondering if you could help to add this functionality?

I tried to include them in the list as in the example below:
bot_follow_list = ['followed_user1', 'followed_user2', 'followed_user3']

But the bot stopped working, I think it only unfollows the ones bot follows. Can you recommend how to make bot unfollow from list provided?

Thanks!

**Comment by LevPasha** [comment]
Hi, you need to learn python. It is simple to make a list user id and run unfollow loop for this list.

**Comment by Kaziusg** [comment]
Thank you for your answer,  would you please assist me with that?

**Comment by LevPasha** [comment]
Look this https://github.com/LevPasha/instabot.py/issues/62

**Comment by Kaziusg** [comment]
Thanks :)
