### ISSUE TITLE
media/popular

### ISSUE THREAD

**Issue by Tonners15** [LevPasha/instabot.py#66]
Hello y'all, I was wondering there is a way to GET media/popular And like certain amount of photos from that section.

**Comment by LevPasha** [comment]
You talk about first 9 photo by tag? If yes - `get_media_id_by_tag` first 9 values that you need.

**Comment by Tonners15** [comment]
does this go inside of the run script get_media_id_by_tag or where do i put it?

**Comment by LevPasha** [comment]
When you run function `get_media_id_by_tag` - this function return list of media_id, like this:
['11111111', '11111112', '11111113', ..., '11111120', '11111121'].

First 9 - is popular, 10-21 is last added.
