### ISSUE TITLE
Resart >>>>

### ISSUE THREAD

**Issue by cahyonegoro** [LevPasha/instabot.py#7]
![capture](https://cloud.githubusercontent.com/assets/16939079/12939152/d8b201b4-cfee-11e5-8c66-50d6aceb0a59.PNG)

**Comment by LevPasha** [comment]
Show me your settings, how you use `InstaBot` class?

**Comment by alvvvvvin** [comment]
@cahyonegoro are you running via IDLE? try running from Terminal directly.
