### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by AinzOal** [LevPasha/instabot.py#71]
First things first thank you LevPasha for your AMAZING contribution. I have some questions if you don't mind? Can instagram notice same IP if say I use multiple account's with this awesome bot? 
If they can, can you point me in direction on how to intergrate proxy inside if it's possible?

Thank you once again.

**Comment by LevPasha** [comment]
@AinzOal hi! Glad that you like my bot!

I can't say somethin 100% about instagram can do and will do. Notice same ip: can? - sure, do? not sure. They have some limits (1000 likes at day and etc.), maybe the have limit 10 or 100 or 1000 accounts frome same ip - i don't know. I have max 5 account from one server at same time and have no problem. There is some service in internet, thet have same functional - maybe they write something about it?

About proxy - i think there is many solution in web.

**Comment by ageorgios** [comment]
self.s = requests.Session()
        self.s.proxies = {"https" : "http://proxyip:proxyport"}

**Comment by LevPasha** [comment]
@ageorgios add this to https://github.com/LevPasha/instabot.py/blob/master/instabot.py#L129

**Comment by gonzalon** [comment]
I tought about the proxy too, thanks for the input about your experience of using 5 at the same time and the change!

**Comment by AinzOal** [comment]
Thanks everybody for great responses. Especially thank you @ageorgios for providing the code. @LevPasha Regarding services and them writing something. I doubt it, but I can assure you that most services like Instagress probably don't use proxy, because they have aprox. 10-100k members for which proxies would hardly suffice(high cost). Instagram probably can't track IP from their stolen API signatures. Anyway if anyone want's I will host their 3 account's for 2 Months on my server in exchange for 1 Virgin Instagram Proxy(not public ones, private ones only). I'm willing to accept up to 60 accounts.in exchange for 20 Proxies. Hit me up at bobotv420@gmail.com
If this isn't allowed I will edit my post.

**Comment by LevPasha** [comment]
@AinzOal i think instagram can track ip in API. They count likes an other, and can track ip.

**Comment by ferhadstack** [comment]
Are sites that are more than 10 thousand users for every five users use a proxy ? Or there is a cheaper way ?

**Comment by hacker0noir** [comment]
thanks for this amazing tool, but i have a problem using proxy, can someone plz show me how? i'm totally new to python, my script is runnung perfectly just wanna know how to add a proxy, thanks.

**Comment by virginsince1997** [comment]
@hacker0noir can I get your private email,  am having problems running thus
script, Please

**Comment by polaroi8d** [comment]
Proxy support added #178

**Comment by wpcbill6** [comment]
> Integrate this into instabot.py
> 
> ```
>     self.s = requests.Session()
>     self.s.proxies = {"https" : "http://proxyip:proxyport"}
> ```

where would i place it in the code?

**Comment by wumbo91** [comment]
> > Integrate this into instabot.py
> > ```
> >     self.s = requests.Session()
> >     self.s.proxies = {"https" : "http://proxyip:proxyport"}
> > ```
> 
> where would i place it in the code?

step 1 search for the file instabot.py then open it in a text editor.
step 2 use the ctrl+f search function to find  "self.s = requests.Session()" without the "" marks, you should see some blue text under this helping you as a template for the layout (do not change the blue text)
step 3 find a http proxy and insert it as this self.s.proxies = {"http" : "http://xxx.xx.xx.xx:xxxxx"} replacing the [x]s with the numbers from the proxy ip and after the (:) replace the [x]s with the port numbers
hope that helps
