### ISSUE TITLE
error in login 'like_per_day' section

### ISSUE THREAD

**Issue by AndyB1928** [LevPasha/instabot.py#73]
# LOGIN CODE #

from instabot import InstaBot

bot = InstaBot(login="*********** *", password="* **********"
               **like_per_day**=1000,
               media_max_like=1000,
               media_min_like=10
               follow_per_day=0,
               follow_time=0*,
               unfollow_per_day=0,
               comments_per_day=0,
               tag_list=['nature', 'green', 'photography', 'tree', 'canon', 'hd', 'beautiful', 'outdoors'
               max_like_for_one_tag = 0,
               log_mod = 0)

bot.new_auto_mod()

getting an error in the syntax for the likes_per_day section shown in bold. am very new to coding so it wouldn't surprise me if this was something simple i'm missing. any help is much appreciated :)

**Comment by LevPasha** [comment]
@AndyB1928 look like you miss `,` after password?

**Comment by LevPasha** [comment]
Check all you write! `,` after all function parameters, and delete all `*`.
