### ISSUE TITLE
Unfollow specifiek groups

### ISSUE THREAD

**Issue by psam25** [LevPasha/instabot.py#76]
Is there a way to unfollow only people who doesn't follow back?

**Comment by LevPasha** [comment]
@psam25 no.

**Comment by psam25** [comment]
Hmm.
What if I use the userinfo.py and compare the ui.get_following() to ui.get_followers() and unfollow those who is not following me?

**Comment by LevPasha** [comment]
If you do it - write your solution here.

**Comment by psam25** [comment]
Ok, no problem.
The problem I have now is that I can't search for an user ID in my own following list.

**Comment by psam25** [comment]
I think this will work

for i in ui.following:
    if ui.following not in ui.followers:
        print(i["id"])

**Comment by psam25** [comment]
Ok no problem.
For so far (without duplication)

```
for i in ui.following:
    d = (i["id"])
    for j in ui.followers:
        f = (j["id"])
        if d == f:
            print(d)  

```
But it gives only the people who are following me already, I can't get i working in reverse.
So people who don't follow me back..

If I use
`if d != f:`
Then I got the ID's [X times the limit function (so with limit 5 I got 5 times the result, duplications)] with the people who following back.. 

Maybe do someone know this problemen.

**Comment by LevPasha** [comment]
```
follower_list = ['1', '2', '3', '4']   
follow_list = ['3', '4', '5', '6'] 
result = list(set(follow_list)-set(follower_list))  
print result 
['5', '6'] #user, that you follow, and they don't follow back.

**Comment by psam25** [comment]
Hmm now I got:
```
for i in ui.following:
    follow_list = (i["id"])
    for j in ui.followers:
        follower_list = (j["id"])
        if follow_list != follower_list:
            result = list(set(follow_list)-set(follower_list))  
            print(result)
```

With the result below, but those are not ID's..
```
[u'0']
[u'9', u'5']
[]
[u'5']
[u'4']
[u'8', u'5']
[]
[u'8']
[u'9']
[u'1']
[u'1', u'0', u'9']
[u'8', u'4']
[]
[u'1', u'8', u'4']
[u'9', u'5']
[u'0', u'8']
[u'0', u'5', u'4', u'8']
[u'0', u'5', u'4']
```

**Comment by LevPasha** [comment]
https://github.com/LevPasha/instabot.py/commit/f9cc58e9a81c951010a102054f0c999fd5aeb874 i think this will help you.
