### ISSUE TITLE
Instagram keeps deactivating the account 

### ISSUE THREAD

**Issue by Gorghor** [LevPasha/instabot.py#79]
Hi LevPasha, 

First of all, congrats on your work!

I'm running into a rather annoying problem. When I run the script locally on my windows machine, it works fine. But when I run it on a distant Linux server, Instagram deactivates the account after 10 or so likes. I then need to reactivate it with an sms code. 

I tried lowering the like per day count, removing follows, hell I even rewrote the script so that it connects to pikore.com and likes/follows through their API connexion (talk about wasted time haha). Nothing doing, still the same problem. Local is fine, dedicated server gets banned. 

The only thing I can still think of is that the Debian machine is running python 2.7.3, which seems to have a problem with SSL requests. I'll upgrade to 2.7.11, but if you have any ideas, I'd be thankful for your input.

All the best,

**Comment by shayanb** [comment]
Please give more details about 'Distant Linux server', are you running it on a dedicated VPS or a cloud based platform or ...?

**Comment by AinzOal** [comment]
Did you make account on server or your computer? Did you run account first on your PC then on server? Try writing anything you do with instagram into notepad(like runned bot at specific time, edited bio etc..) you can easily come to conclusion what's triggering checkpoint.

**Comment by LevPasha** [comment]
@Gorghor Hi!
Some of user have problem with sms:
```
When you get 10k.
and you login it, it will show you profile for 3 secs
and then phone verification will pop-up.
To verify.
Bot won’t work anymore.
Once you verify, you are fine.
When you start the bot again, verification pops-up again, and so on.
```
 There is solution:
```
Enable & disable the 2 factor authentication and it got fixed.
```

**Comment by Gorghor** [comment]
Hey guys, thanks for your responses. 

@shayanb It's just a normal dedicated server I use for work. It runs Debian and has a fixed IP. However it is not located in my home city, which may be raising flags.

@AinzOal made the account on my phone, regularly use it there too. Each time I verify the account, I can then restart the bot and it runs for about 5 to 15 like iterations. After a while nothing happens anymore and when I check from my phone, I get the phone authentication request. 

@LevPasha I'm not sure what you mean by "2 factor authentication". In Instagram? Where can that be found?


For the time being, I've resolved the problem by just running the bot from an old android table using QPython. It's been running overnight without any issues.

**Comment by sfantu** [comment]
My account was created on an emulator and worked fine. Then When i logged in with the example script the account got disabled after one like. I haven't followed more than 15 people in the emulator.

**Comment by LevPasha** [comment]
@shayanb hi! I don't know what is problem. Other hundreds of users work fine.

**Comment by shayanb** [comment]
@LevPasha wrong tag :) @sfantu

**Comment by sfantu** [comment]
@shayanb yeah the second account i made is running for over 12 hours now . Tomorrow i will test if it lasts if i move it to a vps.
