### ISSUE TITLE
Comments and likes

### ISSUE THREAD

**Issue by jaguar754** [LevPasha/instabot.py#8]
How to setup comments and likes? 
I mean to comment every liked photo.
Thanks

**Comment by LevPasha** [comment]
Hi. I will write it soon. For now you can make this:
FInd 192 str in last version of InstaBot https://github.com/LevPasha/instabot.py/blob/master/instabot.py#L192
`like = self.like(self.media_by_tag[i]['id'])` 
and add after it 
`comment = self.comment(self.media_by_tag[i]['id'], 'Your comment')`
i think it will work. 
Be careful, i dont know limit of comment in one day, instagram can ban you!
