### ISSUE TITLE
follows the same id

### ISSUE THREAD

**Issue by nickpettican** [LevPasha/instabot.py#81]
Hi LevPasha,
Thank you for this amazing script.

However I ran into a problem: it only follows one user ID over and over.

For example: 
Trying to follow : 123456
Followed: 123456
Trying to follow: 123456
Followed: 123456
etc

It only changes the ID after I restart the script. Any solutions?

**Comment by nickpettican** [comment]
Update: I found that by letting the bot "like" posts, instead of exclusively just "follow" people, then it does change user IDs.

**Comment by nickpettican** [comment]
New issue, I thought I would leave it here since its related to the "following":

When cleaning up, the script only unfollows 50% of the followed users. I had a look at the code but I can't see where it goes wrong. It will unfollow and then when it reaches half of the follow counter it will stop and log out. It throws an Exception KeyError (in threading), could this be the issue?

**Comment by LevPasha** [comment]
@nickpettican
1) maybe you use bad hastag? Try something like #cat or #car.
2) I don't understand you.
3) I know about it, think about solution.

**Comment by nickpettican** [comment]
Sorry if I was confusing.
When I set the "like_per_day=10", "follow_per_day=1000" and  "unfollow_per_day=1000" just to run for 2 or 3 hours it only followed one ID. When "like_per_day=1000" it follows different IDs. That is OK now.

The issue is when I press ctrl + c to interrupt the script it starts unfollowing, but when the unfollow counter reaches half of the follow counter it logs out. So if the follow_counter = 100 when the unfollow_counter = 50 it stops and it logs out.

**Comment by LevPasha** [comment]
1) Yeah, `like_per_day` create list of `user_id` to follow - this is my mistake, try to change it in future.
2) 1000 follow is too much, instagram will ban you. Use 300-400.
3) Solve it when i will have time.

**Comment by psam25** [comment]
You can try to make an output file liked.txt, put the liked ID's there and compare the ID's with an IF statement (so you never like more than one time the same person)?

**Comment by rekordz** [comment]
I noticed the bot follows and likes certain users and medias and then starts to repeat the list as a cycle. why? log attached

**Comment by LevPasha** [comment]
@rekordz you use not popular hastag.

**Comment by rekordz** [comment]
@LevPasha what is the problem if you do not use a popular hashtag?

**Comment by rekordz** [comment]
@LevPasha @nickpettican 
To be more clear: While using the code/bot what is the difference of a hashtag with 20 million pictures and a hashtag with 2 thousand pictures ? I don't understand, there shouldn't be any difference.

**Comment by nickpettican** [comment]
Because a tag with only 2k pics means that not a lot of people will upload new pics with that tag, so when you refresh the "recent" section of the tag search page you will most likely see the same pics plus just a few new ones; so your bot will re-like some pics. With tags with 1m+ you are more likely to see new pictures on the "recent" section of the tag search page, so your bot has more pics to like. :grin:
Try it out. Go to the search page, put your tag, refresh after 5 minutes and see if there are any new pics. :wink:

**Comment by rekordz** [comment]
@nickpettican hey thanks for the reply. I understand this tag won't get new pics fast but wouldn't the bot like the remaining old 2k pics? As you can see in my log attached above the bot liked 15 pics and then started to loop, liking the same 15 pics, over and over again. What about the remaining 1985 pics? I assume the bot will like most recent until the oldest. I'm I missing something here?

**Comment by nickpettican** [comment]
Most likely the bot only likes the first 15 pics of the "recent" tag page.. I don't know if you can do anything to fix it because it's Instagram's design to only include the first 15 pics, and then you would manually click the "view more" to view the rest.. sorry man 😕

**Comment by rekordz** [comment]
@nickpettican hey, thanks! actually, on the tag page, they only include 12 pics before you have click on load more, I've just checked.

@LevPasha can you confirm it works like this? when you retrieve the list of pics to like by hashtag it only returns 12 or 15 recent pictures and not the full list of media ids on hashtag?

it doesn't make a lot of sense to me

**Comment by LevPasha** [comment]
@rekordz confirm. When i write bot, i can't make pagination by tag, and have no time to this now.
