### ISSUE TITLE
24 hours ban

### ISSUE THREAD

**Issue by DeimosSolden** [LevPasha/instabot.py#83]
Greetings! First of all thank you for the best instagram bot I have found.

I am running your bot on my old iPhone in a mobile terminal (installed from Cydia). It is always charging and the script is being executed 24/7.

The problem I have is that from time to time I get a 24 hour block on some actions (likes/follows/unfollows). It is ok if these are only likes, but when the bot is not able to unfollow people, they just pile up and sometimes I find in the morning that i am following more than a thousand people and I am not even able to unfollow them for another day or even more.

I am using these settings: 750 likes, follows and unfollows per day, no comments, 1 tag. I thought the numbers are not so big to be considered "agressive", but still I get bans and then have to unfollow thousands of people manually.

I thought about running some counter variable to stop performing like/follow/unfollow if it fails a few times in a row, but my python skills are not so good and I am afraid of ruining the code.

Would you kindly advice me on a better bot settings and/or implement sort of a 24 hour break in case of a ban.

**Comment by gonzalon** [comment]
I'm not sure if your configuration, it's the problem, but you should try another configuration first.
I have a something like 1k likes, 250 un/follow and comments, and no problems so far.

Anyway if you still want to make a change, maybe you can try to add something like the except in ```get_media_id_by_tag```:

```
                except:
                    self.media_by_tag = []
                    self.write_log("Except on get_media!")
                    time.sleep(60)
```

And add the ```time.sleep(X)``` to make it sleep.

But I don't think this would apply for most of us.

**Comment by LevPasha** [comment]
@DeimosSolden @gonzalon yeah, i think 750 un/follow is too much.

**Comment by rekordz** [comment]
unfollow numbers depend on the size of your account...big accounts will have larger unfollow limits for the obvious reasons.
