### ISSUE TITLE
Unfollow trouble

### ISSUE THREAD

**Issue by velvetflower** [LevPasha/instabot.py#85]
Привет @LevPasha.

В траблах уже была похожая тема - там у парня отписка переставала работать.
У меня схожая проблема. 
Но вот только я использую функцию unfollow отдельно от общего алгоритма бота.

Я набросал простенький отписчик от "лишних" подписок на основе твоего userinfo, который помещает разницу текущих и нужных мне подписок в список.
И задал bot.unfollow(list) с таймером в 15 +- 15 секунд (как говорится в лимитах: от 15 до 30сек не будет бана).

Но в итоге, бот отписывается каждый раз от разного количества человек.
bot.unfollow(list) перебирает по одному id юзеров и в какой-то момент от функции unfollow в боте перестает приходить ответ "Unfollow id count", в то время как bot.unfollow продолжает отправлять туда id с рандомным перерывом. И такое "молчание" продолжается обычно до окончания списка.

С чем это может быть связано?
Буду благодарен за совет.

**Comment by LevPasha** [comment]
@velvetflower привет, уже не от первого человека слышу про проблему с унфоллоу. Сам пользуюсь только лайками и с таким сам не сталкивался. Будет время - постараюсь попробовать. 
Я думаю инстаграмм банит за слишком частые унфоллоу - попробуй изменить задержку.

`(как говорится в лимитах: от 15 до 30сек не будет бана)` - это ты из описания взял?

Хорошо бы было, если бы ты поделился решением с `простенький отписчик от "лишних"` народу бы пригодилось. Спасибо!

**Comment by velvetflower** [comment]
@LevPasha я немного разобрался с проблемой отписок.
Если со смартфона отписываться от 100 и более подряд (довольно быстро) - следующие нажимания кнопки отписки ни к чему не приводят (кнопка меняется на "отписался" и тут же возвращается на "подписано"). Это исправляется закрытием и открытием приложения. То есть, в теории, при отсутствии ответа от bot.unfollow можно делать логаут и следом логин, после чего продолжать по списку. Попробую это реализовать. И еще гляну что с изменением задержки в большую сторону.

> (как говорится в лимитах: от 15 до 30сек не будет бана) - это ты из описания взял?

Это я нагуглил несколько сайтов с инфой по ограничениям отписок инстраграмма в 2016. Везде инфа разнится, но в целом все сходятся во мнении 15-30 секунд.


> если бы ты поделился решением

Сюда код запостить или новым файлом в проект залить?

**Comment by LevPasha** [comment]
@velvetflower пулл реквест делай. Хм, проверь с перелогином - интересно!

**Comment by velvetflower** [comment]
> проверь с перелогином

Проверил. Не выходит. 
Получается все то же самое, только бот при получении пустого ответа от bot.unfollow() просто перелогинивается до тех пор, пока снова не сможет отписаться.
Пока вижу выход из ситуации в выставлении задержки 30+-30.

**Comment by LevPasha** [comment]
@velvetflower понятно, спасибо!
