### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by Houba28** [LevPasha/instabot.py#86]
is it possible to remove tags and like everything people I am following post on instagram?  @LevPasha

**Comment by LevPasha** [comment]
@Houba28 like post of user that you followed? You should use `userinfo.py` - and write your code.

**Comment by amir4949** [comment]
Can anybody do it? to edit  userinfo.py to like following list posts?

**Comment by Houba28** [comment]
I commented this yesterday, maybe it didnt worked, so again... I made my own bot, so if LevPasha dont mind, I could paste here adress of github page with mine bot using selenium and python, but its not there, maybe I will put the bot on github... or maybe not, It wasnt for me, I have to ask...

**Comment by LevPasha** [comment]
@Houba28 if this work not on my Instabot.py - you should create you github reppo and make there what you want.

**Comment by Houba28** [comment]
yes, I wanted to make my own repo, not uploading my bot to yours, dont worry ;)
