### ISSUE TITLE
Многопоточность

### ISSUE THREAD

**Issue by Miando** [LevPasha/instabot.py#88]
Привет. Можно ли сделать бот для одновременной работы с несколькими аккаунтами ? Подскажите плиз в какую сторону копать. Спасибо

**Comment by LevPasha** [comment]
@Miando Привет. Проще всего создать несколько файлов с конфигурацией и запускать их раздельно. Я пробовал делать через 1 с многопоточностью, но там какие-то косяки были, уже и не вспомню. Сейчас запускаю несколько файлов = несколько аккаунтов.

**Comment by Miando** [comment]
Спасибо большое за ответ
