### ISSUE TITLE
instafeed.js

### ISSUE THREAD

**Issue by mieburungdara** [LevPasha/instabot.py#96]
hi levpasha
Can you build new userinfo and unfollowpub with instafeed.js?
I think we can replace ink361 with instafeed.js to solve userinfo and unfollowpub problem...
sorry for my english :)

**Comment by gonzalon** [comment]
First of all, that library is written in JS, so I don't know how would you manage to do the integration.
But nevertheless you need the client id key to use this library.

**Comment by LevPasha** [comment]
@mieburungdara @gonzalon i start to write this https://github.com/LevPasha/Instagram-API-python. I need help to rewrite bot to work with.
